### ISSUE TITLE
Typo in the doc?

### ISSUE THREAD

**Issue by rackaam** [vriad/zod#1]
Hi!

Awesome work on this lib, I was waiting for years for someone to tackle this problem ;)

```js
const dogsList = z.array(dogSchema);

dogsList.parse([
  { name: "Cujo", neutered: null },
  { name: "Fido", age: 4, neutered: true },
]) // passes

dogsList.parse([]) // passes
```
I believe this shouldn't pass because of the lack of `age` in the first item right?

**Comment by vriad** [comment]
Very true - fixed!

**Comment by wahajahmed010** [comment]
[throttle-probe] zod check

**Comment by wahajahmed010** [comment]
[throttle-probe — please ignore]
