### ISSUE TITLE
Why the necessity of strictNullChecks?

### ISSUE THREAD

**Issue by lonewarrior556** [vriad/zod#102]
Hey great lib, but I cannot use it. 
Currently our project does not have `strictNullCheck` enabled.
Adding validation is a first step in increasing type safety to eventually have `strictNullChecks` 

I understand

```ts
type Dog = {
  name:string | undefiend;
  neutered: boolean  | undefiend;
}
```
means nothing without strictNullChecks, However

```ts
type Dog = {
  name?: string;
  neutered?: boolean;
}
```

Does. 

Is it a technical limitation to treat these two cases the same way?

**Comment by lonewarrior556** [comment]
For Context with strictNullChecks turned off
![image](https://user-images.githubusercontent.com/4774405/88558872-205d9900-cffa-11ea-8806-4b2bd6a0c209.png)

**Comment by vriad** [comment]
I would consider both of those scenarios as “not working” but if you’re satisfied with those typings, then there’s no technical reason why you can’t use Zod. One of the primary design goals behind Zod was an emphasis on rigorous correct types so I’ll never officially recommend usage of Zod without strictNullChecks but it sounds like it’s the right call for your scenario ✌️
