### ISSUE TITLE
Typed key signature for object schemas

### ISSUE THREAD

**Issue by hesyifei** [vriad/zod#104]
In TypeScript, one can do this
```ts
type MyType = {
  requiredKey1: string;
  requiredKey2: number;
  [extraKeys: string]: string;
};
```
such that `requiredKey1` and `requiredKey2` are required and additional keys with `string` values can also be added.

Is there a way to achieve this with Zod?

It seems that `.nonstrict()` only supports the values being `any`, as shown in the doc:
```ts
const dogSchemaNonstrict = dogSchema.nonstrict();

type NonstrictDog = z.infer<typeof dogSchemaNonstrict>;
/*
{
  name: string; 
  neutered: boolean;
  [k:string]: any;
} 
*/
```

Is it possible to support requiring specific type for nonstrict object? Maybe add an optional parameter to `.nonstrict()`? Something like this:

```ts
const dogSchemaNonstrict = dogSchema.nonstrict(z.number());

type NonstrictDog = z.infer<typeof dogSchemaNonstrict>;
/*
{
  name: string; 
  neutered: boolean;
  [k:string]: number;
} 
*/
```

---

(While `Record` with `.refine` can certainly achieve the functionality, inferring its TypeScript type will lose the information of the required fields (and their values' types).)

**Comment by vriad** [comment]
I think this is a really good idea! I'll try to put this into zod@1.11 — should get published in the next week.

Unfortunately I can't think of any workaround currently that would give you the correct inferred type :/

**Comment by vriad** [comment]
As it turns out this type isn't allowed in TypeScript. Which is too bad because I really liked this concept :/
 
```ts
type myType = {
  name: string; 
  neutered: boolean;
  [k:string]: number;
} 
```
From https://www.typescriptlang.org/docs/handbook/interfaces.html:

![Screen Shot 2020-09-15 at 7 55 10 PM](https://user-images.githubusercontent.com/3084745/93287301-033d7f00-f78e-11ea-9aef-dcb9ddf190c2.png)

So I'm gonna close this 🤙
