### ISSUE TITLE
Generic for parsing objects

### ISSUE THREAD

**Issue by kevinsimper** [vriad/zod#105]
Really enjoy the library! Thank you for the work!

To easier debug when a parse fails, I made a small wrapper like this:
```
function parse(parser, obj) {
  try {
    return parser.parse(obj);
  } catch (e) {
    console.log(obj);
    throw e;
  }
}
```

The problem is that typescript can not infer this function.

I tried multiple combinations but can not seem to get it right.

I looked through issues already mentioning generic and did fine one small example: https://github.com/vriad/zod/issues/93 but it did not help fully.

```
function parse<K, T extends z.ZodType<K, any>>(parser: T, obj): K {
  try {
    return parser.parse(obj);
  } catch (e) {
    console.log(obj);
    throw e;
  }
}
```
```
function parse<T extends z.ZodType<any, any>, K typeof T>(parser: T, obj): K {
  try {
    return parser.parse(obj);
  } catch (e) {
    console.log(obj);
    throw e;
  }
}
```
```
interface Schema<T> {
  parse: (data:unknown): T;
  check: (data:unknown): data is T;
}
function parse<T extends Schema<K>>(parser: T, obj) {
  try {
    return parser.parse(obj);
  } catch (e) {
    console.log(obj);
    throw e;
  }
}
```

```
interface SchemaVal {
  parse<K>(data: unknown): K;
}

function parse<T extends SchemaVal>(parser: T, obj): K {
  try {
    return parser.parse(obj);
  } catch (e) {
    console.log(obj);
    throw e;
  }
}
```

**Comment by vriad** [comment]
Hey Kevin,

Good question. Generics are very fussy. I need to do a better job documenting how to write generic helper functions like this. Here's how to do what you want:

```ts
export const parse = <T extends z.ZodType<any,any>>(schema: T, data: unknown): T['_type'] => {
  try {
    return schema.parse(data);
  } catch(err) {
    // handle error here
  }
} 
```

Though I think a "parse factory" pattern would be even better so you don't need to keep passing the schema as an argument to parse:

```ts
export const parseFactory = <T extends z.ZodType<any, any>>(schema: T) => (data: unknown): T['_type'] => {
  try {
    return schema.parse(data);
  } catch (err) {
    // handle error
  }
};
```

Then you can use it like this:

```ts
const User = z.object({ name: z.string() });
const parseUser = parseFactory(User);
const myUser = parseUser({ name: 'billy jean' });
```

**Comment by chrbala** [comment]
I have written this which has somewhat different goals as the above example, which may be of interest to people:
* Intentional (validation) errors returned, not thrown. This distinguishes them from unintentional errors which are still thrown.
* Semi-strongly typed errors (properties known, but not enumerated).
* Always async
* Not concerned with creating factories, can curry if desired
* Decoupled from Zod. Returns errors that are not library specific.

```ts
import { Schema, ZodError, ZodErrorCode } from 'zod';

const asError = (e: unknown) =>
  e instanceof Error ? e : typeof e === 'string' ? new Error(e) : new Error();

export type ExecResult<T> =
  | {
      success: true;
      data: T;
    }
  | {
      success: false;
      error: Error;
    };

export const safeExec = <T extends any>(cb: () => T): ExecResult<T> => {
  try {
    return { success: true, data: cb() };
  } catch (e) {
    return { success: false, error: asError(e) };
  }
};

export const safeExecAsync = <T extends any>(
  cb: () => Promise<T>
): Promise<ExecResult<T>> => {
  // check for sync errors
  const res = safeExec(cb);
  if (!res.success) return Promise.resolve(res);

  return Promise.resolve(res.data).then(
    data => ({ success: true, data }),
    error => ({ success: false, error: asError(error) })
  );
};

type ParseError = {
  code: string;
  path: Array<string>;
};
type ParseResult<T> =
  | { success: true; data: T }
  | { success: false; errors: Array<ParseError> };
export const parse = async <T>(
  schema: Schema<T>,
  data: unknown
): Promise<ParseResult<T>> => {
  const res = await safeExecAsync(() => schema.parseAsync(data));
  if (res.success) return res;

  if (res.error instanceof ZodError) {
    return {
      success: false,
      errors: res.error.errors.map(({ code, message, path }) => ({
        path: path.map(String),
        code: code === ZodErrorCode.custom_error ? message : code,
      })),
    };
  }

  throw res.error;
};
```

Usage:
```ts
const parsed = await parse(MySchema, someValue);

if (!parsed.success) {
  return {
    __typename: 'InputError',
    errors: parsed.errors,
  };
}

// parsed.data is known to exist statically now because of the guard above.
```

**Comment by vriad** [comment]
Open to putting something like this in core. What do you think of `.safeParse()` as the method name?

**Comment by chrbala** [comment]
Seems to make sense to me at least. Would it be ``.safeParse()`` and ``.safeParseAsync()`` when async parsing is added then?

**Comment by vriad** [comment]
Yep. Async parsing is a rabbit hole I haven't quite hit the bottom of. I think it's going to end up inspiring a big refactor.

**Comment by vriad** [comment]
@chrbala look good? it's not exactly what your code does because it returns a single ZodError instead of multiple Errors.

```ts
safeParse: (
    x: unknown,
    params?: ParseParams,
  ) => { success: true; data: Type } | { success: false; error: ZodError } = data => {
    try {
      const parsed = this.parse(data);
      return {
        success: true,
        data: parsed,
      };
    } catch (err) {
      if (err instanceof ZodError) {
        return {
          success: false,
          error: err,
        };
      }
      throw err;
    }
  };
```

**Comment by chrbala** [comment]
Yeah, that seems about right for the sync implementation. It does look like ``params`` is unused though - not sure if that was intentional.

**Comment by vriad** [comment]
Not intentional! Good catch.

**Comment by alvarlagerlof** [comment]
> I have written this which has somewhat different goals as the above example, which may be of interest to people:

This is great, but I can't get it to work with zod objects that have been transformed. Do you know what is missing to allow that?

**Comment by rupertbates** [comment]
I was looking for a solution similar to the original one in this thread - a generic parse function. While the solution given above which looks something like this:
```typescript
const anyParse = <T extends z.ZodTypeAny>(
  schema: T,
  data: unknown,
): z.infer<T> => {
  return schema.parse(data);
};
```
does work, it results in a linting error on the return statement `Unsafe return of an `any` typed value`

By working through the types I came up with this version which doesn't have that issue, hopefully it will help someone else:
```typescript
const typeParse = <I, O, T extends z.ZodType<O, z.ZodTypeDef, I>>(
  schema: T,
  data: unknown,
): z.infer<T> => {
  return schema.parse(data);
};
```
