### ISSUE TITLE
type with fixed values

### ISSUE THREAD

**Issue by dillonbhola** [vriad/zod#116]
is there a way to convert a typescript type with fixed values to a zod schema? 

some components from external libraries contain props with  types like below:
```js
type AcceptedValues = 1|2|3|4|5|6|7|8|9|10|11|12;
```

I would like to validate data so I can pass it to the component.
Here is what I tried:
```js 
type AcceptedValues = 1|2|3|4|5|6|7|8|9|10|11|12;
const mynumber = zodNumber().positive().min(1).max(12);

export const validateNumber = (data: unknown): AcceptedValues => { 
	try {
		return mynumber.parse(data);
	} catch (error) {
		if (error instanceof ZodError) {
			console.log(error.errors);
		}
	}
	return 12;
};
```
The error of the first return in validateNumber: `Type 'number' is not assignable to type 'AcceptedValues'.`

**Comment by vriad** [comment]
Good question. To do this I recommend casting to `z.Schema<CustomType>`:

```ts
type AcceptedValues = 1|2|3|4|5|6|7|8|9|10|11|12;
const mynumber:z.Schema<AcceptedValues> = z.number().min(1).max(12);
mynumber.parse(5); // type: AcceptedValues
```
