### ISSUE TITLE
Export InvalidUnionError type

### ISSUE THREAD

**Issue by maneetgoyal** [vriad/zod#118]
I am currently making a utility function for a use case to specially handle union errors. The error object is a bit nested in my situation so feeling the need for that. **Can `InvalidUnionError` be exported as a type from the library?** Otherwise finding it a bit difficult to deal with it in TS.

For instance, I have:

```ts
function findUnionError(zodError: zod.ZodError): ZodSuberror | undefined {
  return zodError.errors.find(err => {
    return err.code === zod.ZodErrorCode.invalid_union;
  })
}
```

It will be great if I can do:

```ts
function findUnionError(zodError: zod.ZodError): InvalidUnionError | undefined {
  return zodError.errors.find((err) => {
    return err.code === zod.ZodErrorCode.invalid_union;
  }) as InvalidUnionError | undefined;
}
```

Because later I need to access the `.unionErrors` property and can't do it:

![image](https://user-images.githubusercontent.com/25290212/90334191-8467f180-dfe9-11ea-8757-703c98dbfb83.png)

I am again needing to do:

```ts
function something(err: zod.ZodError): void {
  const errorItem = findUnionError(err);
  if (errorItem !== undefined && errorItem.code === zod.ZodErrorCode.invalid_union) {
    // do something with errorItem.unionErrors
    errorItem.unionErrors
  }
}
```

which feels like a little extra steps.

**Comment by vriad** [comment]
Are you just trying to print a custom error? If so the recommended way to do this is with a custom error map.

```ts
const errorMap: z.ZodErrorMap = (error, ctx) => {
  switch (error.code) {
    case z.ZodErrorCode.invalid_union:
      console.log('CUSTOM UNION ERROR ');
      error.unionErrors; // InvalidUnionError
      return { message: 'my custom union error' };
  }

  // fall back to default message
  return { message: ctx.defaultError };
};

z.string()
  .optional()
  .parse(12, { errorMap })

// error.message = "my custom union error"
```

Let me know if your use case is different. I'm happy exporting these interfaces from the library but not if it encourages bad practices relating to error generation. Error maps are a powerful abstraction that are massively underutilized.

**Comment by maneetgoyal** [comment]
Thanks @vriad for your response and sorry for the delay. I am simply using Zod with formik and had some invalid union errors. Flattening the ZodError with `.formError` property wasn't giving that informative messages. So needed to modify them a bit. The ZodErrorMap looks like a good way out. Will try it and get back.

**Comment by maneetgoyal** [comment]
@vriad 

>Are you just trying to print a custom error? If so the recommended way to do this is with a custom error map.

No, I am trying to access a deeply nested error in a `ZodSuberror` with error code `ZodErrorCode.invalid_union`. I tried using `ZodErrorMap` but the thing it seems to be good at is modifying the error messages. In my use case, I am not altering the error message. The issue is that the error message I am interested in extracting is quite deep:

- I get a `InvalidUnionError`.
- Then I go to its `.unionErrors` property which is an array of `ZodError`.
- In that, I am only interested in the ZodError which has the smallest `.errors` array size.
- In that smallest `ZodError`, the `ZodSuberror` I am interested in is again a `InvalidUnionError`.
- Finally, I am interested in that error message: `smallestError.errors[0].path` & `smallestError.errors[0].message`.

---

For achieving it, one of the utility function I made is this:

```ts
/**
 * Checks whether a given Zod error has a sunion type sub error
 * @param err
 */
export function findZodUnionError(
  err?: zod.ZodError
): InvalidUnionError | undefined {
  let unionError: InvalidUnionError | undefined;
  if (err !== undefined) {
    unionError = err.errors.find((subErr) => {
      return subErr.code === zod.ZodErrorCode.invalid_union;
    }) as InvalidUnionError | undefined;
  }
  return unionError;
}
```

So if `InvalidUnionError ` is exported natively, it will be quite useful in my case. Any other suggestion is also greatly appreciated.

**Comment by vriad** [comment]
As of zod@1.11 `InvalidUnionError` and all other suberror data types are now exported

**Comment by alfonmga** [comment]
> @vriad
> 
> > Are you just trying to print a custom error? If so the recommended way to do this is with a custom error map.
> 
> No, I am trying to access a deeply nested error in a `ZodSuberror` with error code `ZodErrorCode.invalid_union`. I tried using `ZodErrorMap` but the thing it seems to be good at is modifying the error messages. In my use case, I am not altering the error message. The issue is that the error message I am interested in extracting is quite deep:
> 
> * I get a `InvalidUnionError`.
> * Then I go to its `.unionErrors` property which is an array of `ZodError`.
> * In that, I am only interested in the ZodError which has the smallest `.errors` array size.
> * In that smallest `ZodError`, the `ZodSuberror` I am interested in is again a `InvalidUnionError`.
> * Finally, I am interested in that error message.
> 
> ```ts
> const smallestError = findSmallestZodError(subError.unionErrors);
> const unionError = findZodUnionError(smallestError);
> if ( unionError !== undefined && unionError.path.includes("something")) {
>    lodash.set(errors, unionError.path, unionError.unionErrors[0].errors[0].message);
> }
> ```
> 
> For achieving it, one of the utility function I made is this:
> 
> ```ts
> /**
>  * Checks whether a given Zod error has a sunion type sub error
>  * @param err
>  */
> export function findZodUnionError(
>   err?: zod.ZodError
> ): InvalidUnionError | undefined {
>   let unionError: InvalidUnionError | undefined;
>   if (err !== undefined) {
>     unionError = err.errors.find((subErr) => {
>       return subErr.code === zod.ZodErrorCode.invalid_union;
>     }) as InvalidUnionError | undefined;
>   }
>   return unionError;
> }
> ```
> 
> So if `InvalidUnionError ` is exported natively, it will be quite useful in my case. Any other suggestion is also greatly appreciated.

Looks like you implemented your own union resolver to get the _right_ errored union. How far it went? did you run into any issue? I'm trying to solve the same _issue_.

BTW thanks for sharing your function, I can see I'm not the only person that are trying to do something similar.

**Comment by maneetgoyal** [comment]
>Looks like you implemented your own union resolver to get the right errored union. How far it went? did you run into any issue? I'm trying to solve the same issue.

I didn't make it too general as my errors were quite nested and I started feeling that the resolution logic can change a lot with each schema. So made the function to do only the stuff that I needed for my narrow use case (described above).
