### ISSUE TITLE
ZodErrorCode not importing correctly

### ISSUE THREAD

**Issue by sayav** [vriad/zod#119]
I get an error when accessing string methods when using React Native with Expo. I've discovered that the error is due to the ZodError file not being imported correctly.

`TypeError: undefined is not an object (evaluating '__1.ZodErrorCode.invalid_string')`

The import is currently `import { ZodErrorCode } from '..'` at zod/src/types/string.ts.

Changing it to `import { ZodErrorCode } from '../ZodError'` fixes the issue.

This works fine in other environments, maybe the babel config that Expo uses is messing things up.

**Comment by vriad** [comment]
Upgrade to zod@1.10.3 and let me know if you're still having issues 👍

**Comment by sayav** [comment]
Wow that was quick! Works perfectly, thanks a lot :)

**Comment by vriad** [comment]
Excellent! Cool to see Zod getting used with React Native :) And thanks for the sponsorship! 🚀
