### ISSUE TITLE
Inferring all object properties as optional

### ISSUE THREAD

**Issue by WolfOfProgramming** [vriad/zod#121]
I have this problem recently, I have this schema
`const ArticleData = z.object({
  title: z.string(),
  date: z.string(),
  tags: z.array(z.string())
});`
But if I check what's the type of it is inferred, I get something like this.
![image](https://user-images.githubusercontent.com/47081011/90552849-bcab3380-e193-11ea-89ee-552bd1e9f953.png)
So in the end parse method gives me this thing:
![image](https://user-images.githubusercontent.com/47081011/90552900-d2205d80-e193-11ea-9691-3f1d86f56791.png)
My version of zod is "^1.10.3".

**Comment by vriad** [comment]
This is almost always related to your tsconfig. Make sure you have `"strictNullChecks": true` in the "compilerOptions" in your tsconfig.json.

**Comment by WolfOfProgramming** [comment]
Thanks a lot, it worked, I had set `strict: false` in default next.js tsconfig.

**Comment by vriad** [comment]
Excellent!

**Comment by nawlbergs** [comment]
can you turn on strict null checks per file?
