### ISSUE TITLE
Strip unknown keys from object schemas by default

### ISSUE THREAD

**Issue by dexx086** [vriad/zod#123]
Hi!

First of all, looks like a great job you did with this library. Looks very clean and developer friendly, and has some features I'm missing from io-ts.
Actually, I extended io-ts with some of them your library offers out of the box, but before I would jumping into and trying whether your library would work in my project, I'd like to ask something in advance to see if I could achieve it with it:
**Is there a way to 'export' a structure (object) that way Zod would delete the keys that are masked out (with `omit`)?**

The use case: I'd like to use Zod to serialize ('export') and unserialize (parse) custom structures (actually React component states, but could happen for multiple other use cases). But sometimes, there are data in the component state which is needed for runtime, but not needed (and I don't want) to serialize/unserialize.

At unserialization, masking is OK, it will ignore the not needed ones if I create a new 'masked' type.
But at serialization... I have the full data structure, and if I serialize it, it would contain all, even masked data as well. That's what I don't want.

An example based on a doc example:

```
const Recipe = z.object({
  id: z.string(),
  name: z.string(),
  ingredients: z.array(z.string()),
});

const NoIDRecipe = Recipe.omit({ id: true });
type NoIDRecipe = z.infer<typeof NoIDRecipe>;

const data: Recipe = { id: 1, name: 'test', ingredients: ['x', 'y', 'z'] };

const serializable = NoIDRecipe.<serialize/export/clean?>(data);
```

Here, I'd like to make a copy of the 'data' variable, but with the NoIDRecipe schema, and in the copy (serializable) structure I want the 'id' keys to be removed, based on the schema (as NoIDRecipe doesn't contain it).
Is it possible somehow?

**Comment by vriad** [comment]
This isn't supported currently because Zod returns the same object you pass in.

Here's a workaround from another issue: https://github.com/vriad/zod/issues/47#issuecomment-625474975

**Comment by dexx086** [comment]
Thanks for your response. The mentioned workaround could work, but only for root level properties, because Object.keys doesn't work in a recursive way, however my (and I think most of our) structures have nested levels of object/arrays/etc.

Even though, if I would (and could) implement a method that would gather object properties recursively, that wouldn't be enough, because filtering out unknown properties cannot work in such simple way. Think about I have a `Map` of X typed objects, and that X type has an omitted key I want to delete. The algorithm should know, and go through each elements, following the schema. So with a simple `_.pick` it's not achievable where such complex structure could be present, I guess.

Doing this filtering would be possible only with following Zod's schema, and implement it for each types. I'm not saying this is a musthave feature that needs to be in the library itself, but as I see there's a 'transformation' feature (in alpha status) being considered, maybe that could cover this case?

Anyway, 2 more tiny question came into my mind that I couldn't quickly find answers for:
- is Map/Set types handled?
- is there some (really) very short explanation why `strictNullChecks` option is required for the library to work? Without that, what functionality would not work properly/at all?

**Comment by vriad** [comment]
Yep this will definitely be possible/supported whenever the transformation API drops. I'm considering a .stripUnknown() convenience method on objects that would set an internal configuration:

```ts
z.object({ 
  asdf: z.string() 
})
  .stripUnknown()
  .parse({ asdf: "hello", qwer: 12 }); // => { asdf: "hello" }
```
Of course this would also be shallow, so you've have to call `.stripUnknown` on all the object schemas in your hierarchy. 

Your other questions:
- There's no built-in support for Maps or Sets. You could probably pass a Map into an object schema without issues...never tried this though. You can use `z.record` to enforce a single schema across all values in an object/map.
- StrictNullChecks is required to infer any non-optional properties in objects. Otherwise every object property is undefined: https://github.com/vriad/zod/issues/121

**Comment by johannessjoberg** [comment]
Looking forward to this feature as an avid `joi` user 🙌 

> Yep this will definitely be possible/supported whenever the transformation API drops.

Is there a timeline regarding this?

**Comment by vriad** [comment]
Zod 2 is now [in beta](https://github.com/vriad/zod/tree/v2) and strips all unknown keys by default! 

@dexx086 @johannessjoberg
