### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by mad-gooze** [vriad/zod#130]
Hi!

Which browsers are officially supported by zod? 
Is it possible to add ie11 support? now zod breaks because it needs `Array.prototype.find`
https://github.com/vriad/zod/blob/d1ae8e3538167a41e13ab6cfc2466ef3ca69e63a/src/parser.ts#L92

**Comment by vriad** [comment]
Just fixed this, upgrade to zod@1.11.1 and let me know if you're still having issues 👍

**Comment by mad-gooze** [comment]
cool, thx!
