### ISSUE TITLE
z.number not working properly when used with z.record

### ISSUE THREAD

**Issue by tamj0rd2** [vriad/zod#131]
I basically have a data structure called rawNcdcConfig which is a record made up of rawServices. Within a rawService, I want a required number field called port.

Example:

```typescript
const rawServiceSchema = z.object({
  configPath: z.string(),
  port: z.number().positive(),
  realApi: z.string().url(),
  rateLimit: z.number().positive().optional(),
})
const rawNcdcConfigSchema = z.record(rawServiceSchema)

const rawDataToParse = {
  Config1: {
    configPath: './my-file.yml',
    port: 5001,
    realApi: 'http://example.com',
  },
  Config2: {
    configPath: './my-file.yml',
    port: 5002,
    realApi: 'http://example.com',
  },
  // this one is missing a port so I expect a validation error to be thrown
  'Another Config': {
    configPath: './my-file.yml',
    realApi: 'http://example.com',
  },
}

const parsedData = rawNcdcConfigSchema.parse(rawDataToParse)
console.dir(parsedData)
```

Output:
![image](https://user-images.githubusercontent.com/20561445/91768039-f12be000-ebd4-11ea-85b6-a9195b43cd2a.png)

If I parse the "Another Config" object directly using the `rawServiceSchema`, it throws as expected:

```typescript
const parsedData = rawServiceSchema.parse(rawDataToParse['Another Config'])
console.dir(parsedData)
```

Output: 
![image](https://user-images.githubusercontent.com/20561445/91768331-5a135800-ebd5-11ea-8179-c61ec60ea0e7.png)

Is this a bug or am I doing something wrong?

**Comment by vriad** [comment]
Good catch! There was a bug in the parser. Fixed in zod@1.11.3 👍
