### ISSUE TITLE
Use nonstrict with unknown instead of any

### ISSUE THREAD

**Issue by lantw44** [vriad/zod#133]
Currently when `.nonstrict()` is used, `[k: string]: any` appears on the inferred type. Is it possible to use `[k: string]: unknown` instead? The problem of using `any` is that TypeScript allows you to do anything on any property. If you have a typo on the property name, an unexpected `undefined` will appear at runtime. If `unknown` is used, at least TypeScript can report an error when you try to use it or assign it to a different variable.

This feature request is similar to https://github.com/vriad/zod/issues/104. I am not sure if this issue will be considered a duplicate of it, but I think `.nonstrict()` will be much safer to use if it uses `unknown` instead of `any` by default.

**Comment by ervasive** [comment]
Also, it can be helpful in cases when schema describes some third party type that it has to conform to.

Maybe `nonstrict` could take a parameter to set the type of unspecified properties?

**Comment by tup1tsa** [comment]
Unknown seems good enough

**Comment by tup1tsa** [comment]
Given that this is a breaking change, we can add an optional parameter to 'optional' call. I think it can be be a bit better. And change 'any' to 'unknown' in the next major version update (there is no reason to keep any)

**Comment by vriad** [comment]
@tup1tsa @ervasive In Zod 2 schemas will be non-strict by default (in that they'll allow unknown keys) so I'm considering getting rid of the index signature altogether. Thoughts?

There will still be a way of "manually" setting the index signature using the approach described here: https://github.com/vriad/zod/issues/104

**Comment by tup1tsa** [comment]
I don't mind the parse return type to be a union with one type describing fields that were validated against and another will be with index signature (with whatever type you want to use, but defaulted to unknown)
I can see that in the 104 issue you have the problem that index signature should not conflict with other properties, but nothing restricts us from using multiple types (a union).
![image](https://user-images.githubusercontent.com/15947136/93330766-f7060000-f827-11ea-9a9c-6949c805c62b.png)

**Comment by tup1tsa** [comment]
I'm having second thoughts again. I think getting rid of 'index signature' completely is a decent idea. 
The only reason why I want to use non-strict zode mode is for it not to fail when new keys are present (for example, if I'm working with external API and they add extra fields to the response, I don't want my app to break completely). I will not use those 'unvalidated' keys (by zod) anyways.

**Comment by tup1tsa** [comment]
@lantw44 Check out my example with using unknown key in the string constuctor (via backquotes). Typescript doesn't complain yet that is definitely a mistake. In some places unknown is still a valid parameter, so I would rather not have it at all (neither unknown, nor any, nor any other type).

**Comment by tup1tsa** [comment]
I think not having index signatures at all is a better idea. 
I don't want to use unknown keys that weren't validated by zod schema. 
Having `[index: string]: unknown` can still cause some problems. You can make a typo and `unknown` type will be used. If the function not that strict, you may not even notice it.
Good example is a string constructor (via backquotes)

```
const unknownObj = {
  [index: string]: unknown
}
const stringWithUnknown = `${unknownObj['anything']}`
```
This will not cause typescript to stall here.

**Comment by vriad** [comment]
Zod 2 is now [in beta](https://github.com/vriad/zod/tree/v2) and sidesteps this issue by getting rid of index signatures altogether. Objects are "nonstrict" by default (in that they allow unknown keys) but the inferred type contains no index signature unless you use the `.catchall()` method to provide one: https://github.com/vriad/zod/tree/v2#catchall
