### ISSUE TITLE
[Question] What is the recommended approach to attach metadata?

### ISSUE THREAD

**Issue by tmtron** [vriad/zod#138]
Note: this is related to #76 which was closed.

So basically we need to attach some arbitrary metadata. The zod definitions and the meta-data should then be used to create an [Open API specification](https://swagger.io/docs/specification/about/).

I do **not** want to support a second tree of objects just for some metadata (note, that the data can be deeply nested) - as explained by @ivan-kleshnin [here](https://github.com/vriad/zod/issues/76#issuecomment-667862512)

The nasty workaround that I use now is to add a dummy refinement (the check-function always returns `true`) that stores our custom meta-info in the `params`.

**Comment by vriad** [comment]
I'm still opposed to this for all the reasons I mention in #76. There are other usability issues as well beyond what I describe there. For instance if you try this:

```ts
z
  .object({ name: z.string() })
  .meta({ number: 12 })
  .optional()
```

The returned schema won't contain the metadata because .optional() returns a new schema without the metadata you've set. So you need to be extra careful with the ordering of your method calls. From a maintainer's perspective, this sort of problem will lead to possibly hundreds of issues over the next many years and I don't want to deal with it. 

You'll have stronger typing and more understandable code by maintaining your metadata externally.

**Comment by tmtron** [comment]
> The returned schema won't contain the metadata because .optional() returns a new schema without the metadata you've set. So you need to be extra careful with the ordering of your method calls. 
 
Yeah, but the meta-data is still available - it's now just one level deeper in the object-part of the new union. To get the meta-data we can use some extra-logic to get the nested data - i.e. you must already do the same thing for [isOptional()](https://github.com/vriad/zod/blob/1.11/src/codegen.ts#L6).  
So we could have methods like: `getFirstMetaData() => any`, `getMetaData() => any[]`

> From a maintainer's perspective, this sort of problem will lead to possibly hundreds of issues over the next many years and I don't want to deal with it.

That is understandable, but IHMHO it's quite an exaggeration. 
In the end it's just a simple readonly property, and the only important thing is to copy it over when you create new instances: the same thing that you must already do for the `checks`: see [refinements](https://github.com/vriad/zod/blob/1.11/src/types/base.ts#L131).  
Hint: you may consider something like [immerjs](https://github.com/immerjs/immer) to make immutability handling easier.

> You'll have stronger typing and more understandable code by maintaining your metadata externally.

Maybe we are talking about 2 different use-cases. I'm talking about simple meta-data, like a title or a description for a field.

e.g. "external metadata"
```ts
const userSchema = z.object({
  firstName: z.string()
    .min(5)
    .max(25)
    .nonempty(),
  name: z.string()
    .min(5)
    .max(25)
    .nonempty(),
});

const userMeta: Record<string, {
  description: string
}> = {
  firstName: {
    description: ' the users first name',
  },
  name: {
    description: 'the users name',
  },
};
```
Compare this to a simple meta-data field:
```ts
const userSchema = z.object({
  firstName: z.string()
    .min(5)
    .max(25)
    .nonempty()
    .meta({
      description: ' the users first name',
    }),
  name: z.string()
    .min(5)
    .max(25)
    .nonempty()
    .meta({
      description: 'the users name',
    }),
});
```

* there is a lot more code when using external meta-data, which makes the code **less understandable**
* to get the types right on the external meta-data (e.g. the keys of the meta-record should not be strings, but `keyof userSchema`) is not so easy: you need to handle nested objects, etc.  
* in real production code, the schema will likely have so many lines that you don't even see the related meta-data (even when it's in the same file) which will cause other issues
  * e.g. when you rename the field `name` to `lastName`, the description is now out-of-sight and it's likely that you forget to update the related description
* when you write some code that needs the meta-data and the zod-info (e.g. min/max boundaries of a check) then it's now more complicated, because you need to iterate over the zod-def and lookup the related meta info, ..

That's just my 2 cents.
I can anyway live with the work around (fake refinement-check).

**Comment by jedwards1211** [comment]
Here's how I accomplish this: https://github.com/colinhacks/zod/issues/76#issuecomment-1887838005
