### ISSUE TITLE
valid object fails to be parsed when using z.intersection

### ISSUE THREAD

**Issue by guigzzz** [vriad/zod#145]
I tried following the intersection example in your README:

```typescript
const HasId = z.object({
    id: z.string(),
});
  
const BaseTeacher = z.object({
    name: z.string(),
});
  
const Teacher = z.intersection(BaseTeacher, HasId);

type Teacher = z.infer<typeof Teacher>;

const t: Teacher = { // compiles ok
    id: '123',
    name: 'hello'
};

Teacher.parse(t); // => throws
console.log('ok');
```
prints the following:
```
2 validation issue(s)

  Issue #0: unrecognized_keys at
  Unrecognized key(s) in object: 'id'

  Issue #1: unrecognized_keys at
  Unrecognized key(s) in object: 'name'
```

if I replace the `Teacher` zod definition with:
```typescript
const Teacher = z.object({
    id: z.string(),
    name: z.string()
});
```
then the object is validated ok.

Am I doing something wrong ? I'm using the latest 1.11.5 version on TS 4.0.2

**Comment by vriad** [comment]
Sorry about that, the documentation is wrong there. The behavior of intersections is quite intuitive when it comes to objects. There are other Issues that have more details about this.

For now just use the .merge or .augment methods.

**Comment by guigzzz** [comment]
ok here's the workaround for my issue: https://github.com/vriad/zod/issues/82

This is really confusing for users, especially if the example in the documentation is invalid or doesn't work in the general case.

I think the documentation for intersection should definitely outline these limitations (or `z.intersection` should simply not exist)

Regardless, thanks for the otherwise great library.

**Comment by vriad** [comment]
I agree intersection shouldn't exist - it'll go away with Zod v2. I took that section out of the docs.
