### ISSUE TITLE
bi-directional virtuals population issue

### ISSUE THREAD

**Issue by grreeenn** [vriad/zod#146]
Hi,

Thanks for your work - Typegoose makes life with Mongo and Typescript a breeze :)

I have a strange issue (probably, because I'm trying to do a strange thing).
In my use case, Users can follow each other, and these relations contain additional properties - so I moved them to the separate model Followship. 

Followship has `followerId` and `followeeId` (both IDs of Users) to define the relation. What I want is an ability to pull the Followships separately and populate Users in them, and also an ability to pull Users with their Followships populated.

So here is how my models look:

User:
```typescript
@modelOptions({
  schemaOptions: {
    toJSON: { virtuals: true },
    toObject: { virtuals: true }
  }
})
export class User {

  @prop({ required: true })
  public name!: string;

  @prop({unique: true})
  public email!: string;

  @prop()
  public password!: string;

  // 
  @prop({
    ref: Followship,
    type: Followship,
    localField: '_id',
    foreignField: 'followeeId',
    justOne: false
  })
  public followers?: Ref<Followship>[];

  @prop({
    ref: Followship,
    type: Followship,
    localField: '_id',
    foreignField: 'followerId',
    justOne: false
  })
  public followees?: Ref<Followship>[];

  public static getById(this: ReturnModelType<typeof User>,
                        id: string
  ): Promise<DocumentType<User> | null> {
    return this.findById(id)
      .select('name email address')
      .populate('followees')
      .populate('followers')
      .exec();
  }
}
```

Followship:
```typescript
@modelOptions({
  schemaOptions: {
    toJSON: { virtuals: true },
    toObject: { virtuals: true }
  }
})
export class Followship {
  @prop({ required: true })
  followerId!: ObjectID;

  @prop({ required: true })
  followeeId!: ObjectID;

  @prop({
    ref: User,
    localField: "followerId",
    foreignField: "_id",
    justOne: true
  })
  public follower?: Ref<User>;

  @prop({
    ref: User,
    localField: "followeeId",
    foreignField: "_id",
    justOne: true
  })
  public followee?: Ref<User>;

  @prop()
  seeFirst!: boolean;

  public static getFollowersOfUser(this: ReturnModelType<typeof Followship>,
                                   userId: string
  ): Promise<DocumentType<Followship>[]> {
    return this.find({ followeeId: userId })
      .populate({ path: "follower" })
      .exec();
  }
}
```

The issue is the following:
When I call `User.getById()`, I get the User object correctly populated with followers and followees (is there a better term for it in English btw?). But when I call `Followship.getFollowersOfUser()`, I get the array of Followships - with `follower: null`.
Debug mode shows, that `Followship.getFollowersOfUser()` tries to find the User ids in the Followship collection, and obviously fails:
```
Mongoose: followships.find({ followeeId: ObjectId("5f5836e2de810118a26bddba") }, { projection: {} })
Mongoose: followships.find({ _id: { '$in': [ ObjectId("5f56808196a0b238cf32fcff") ] } }, { skip: undefined, limit: undefined, perDocumentLimit: undefined, projection: {} })
```

The thing is, that if I remove the virtual fields from User model, `Followship.getFollowersOfUser()` returns just fine:
```
Mongoose: followships.find({ followeeId: ObjectId("5f5836e2de810118a26bddba") }, { projection: {} })
Mongoose: users.find({ _id: { '$in': [ ObjectId("5f56808196a0b238cf32fcff") ] } }, { skip: undefined, limit: undefined, perDocumentLimit: undefined, projection: {} })
```

Am I doing something wrong, or is there a workaround for this? Except using only the User's virtuals

**Comment by grreeenn** [comment]
holy banana, I've opened the issue in the wrong repo.

@vriad, Zod is even more awesome than Typegoose!!!

**Comment by vriad** [comment]
Hahaha I don’t know about that 😂 typegoose is pretty great!

**Comment by grreeenn** [comment]
Both are awesome, but your lib was like a take of fresh air when I found it. So seamless and simple :) the only thing I wish that was there is an ability to serialize/deserialize shapes to pass them through API (to keep server and client validation in sync), but I understand what complexity does it introduce (especially with custom, `.refine` validations), so I didn't even open a feature proposal :)
