### ISSUE TITLE
Error message formatting

### ISSUE THREAD

**Issue by jstaro** [vriad/zod#150]
Currently, the error message is generated with `./index` as a separator when joining the path segments of an error, making the message quite difficult to read (especially when you have many path segments).

`[0, 'status']` gives: `Issue #1: invalid_enum_value at 0./indexstatus`

I feel this should either be `/` or `, `, or is there a specific reason for this? It looks like part of an import path, so maybe some editor shenanigans?

**Comment by vriad** [comment]
Oops! Find & replace fail 😬 

Fixed in zod@1.11.6 👍
