### ISSUE TITLE
Combine min() and optional()

### ISSUE THREAD

**Issue by JanRuettinger** [vriad/zod#151]
It would be helpful if you could combine min() and optional().

Let's say you have a password field that can either be filled out with at least 6 characters or not at all.

The straightforward solution doesn't work unfortunately since I also get an error when the field is not filled out.
```js
const userUpdateSchema = z.object({
  password: z.string().min(6).optional(),
});
```

Can this be implemented?

**Comment by sylvanaar** [comment]
I was testing optionality today - so I tried your example - it works for me

```ts
    const userUpdateSchema = z.object({
        password: z.string().min(6).optional(),
      });
  
    userUpdateSchema.parse({ password: "123456" });   // OK
    userUpdateSchema.parse({});                       // OK
```

**Comment by vriad** [comment]
This is working for me as well.

Upgrade Zod to the latest version and see if the error persists. If so provide more information about the error you're getting. 👍
