### ISSUE TITLE
default() function missing?

### ISSUE THREAD

**Issue by tmtron** [vriad/zod#157]
The [docs](https://github.com/vriad/zod#default-values) mention that we can use `default()`:

> Equivalently you can express this using the built-in .default() method, available on all Zod schemas.
> 
> z.string().default('default value');

but that seems not to exist.  
e.g. `z.string().default('abc')` does not compile

My zod version `1.11.8`

Is it a bug or am I missing something?

**Comment by tmtron** [comment]
ah - [found it](https://github.com/vriad/zod/blob/b3e89512eb5f6d0caf1e04609834cd96a795480a/src/types/base.ts#L289).

Seems it's a V2 feature.

**Comment by vriad** [comment]
Sorry, must have accidentally copy/pasted the v2 readme over to master 😬  Fixed now.
