### ISSUE TITLE
.safeParse() and generics

### ISSUE THREAD

**Issue by grreeenn** [vriad/zod#159]
Hi,

I have a quick question.

I want to wrap `safeParse()` into a utility method, that gets an `unknown` object, `ZodObject` and returns the parsed data if succeeded, like this:

```
export const shapeObject = (object: unknown, zodObject: AnyZodObject) => {
  const validationResult = zodObject.safeParse(object);
  if (validationResult.success) {
    return validationResult.data;
  } 
  
  return null;
}
```

The question is, what is the correct way to type such a method? Can I somehow use generics to know what will it return?

Thanks,

**Comment by grreeenn** [comment]
okay, I wrote some nonsense. Please disregard

**Comment by vriad** [comment]
This is possible, let me know if you're still having trouble
