### ISSUE TITLE
No unknown keys

### ISSUE THREAD

**Issue by vriad** [vriad/zod#16]
This feature causes yup to throw an error on validation if there's a property on the object that doesn't match the schema. Similar to `yup.object().noUnknown()` 

Split off from #14.

**Comment by christophemarois** [comment]
I don't know if you'd consider also adding yup's `stripUnknown` option, which is related to the `noUnknown()` behavior, but is not treated as an error.

This would be a really useful feature for my particular use-case: I have React components that take as a prop an object with circular dependencies (think ActiveRecord). I currently use yup with  to do both prob validation and "picking" properties, so I end up with an object that is serializable, that I can send over HTTP, and that only contains the property I need.

I have a working workflow with yup, but the lack of optional types and correct type inference is problematic.

Extremely dumb yup example to illustrate my point: 

```javascript
import { object, number } from 'yup'

let a = { val: 1 }
let b = { val: 2 }
a.b = b
b.a = a

const schema = object({
  val: number(),
  b: object({
    val: number(),
    a: object({
      val: number()
    })
  }),
})

schema.validateSync(schema, { stripUnknown: true })
// => { val: 1, b: { val: 2, a: { val: 1 } } }
```

**Comment by vriad** [comment]
@christophemarois I've been thinking out this a fair bit.

I think I'll introduce a `.mask()` method on object schemas that lets you pass in a properly typed instance and get back a new object with some subset of the properties. Like so:

```ts
const Dog = z.object({
  name: z.string(),
  age: z.number()
})

const justName = Dog.mask({ name: true }, { name: "Fido", age: 20 });
// => { name: string }
```

In your situation I'd recommend creating a proper recursive type for the sake of representational accuracy:

```ts
interface A {
  val: number;
  b: B;
}

interface B {
  val: number;
  a: A;
}

const A: z.ZodType<A> = z.lazy(() =>
  z.object({
    val: z.number(),
    b: B,
  }),
);

const B: z.ZodType<B> = z.lazy(() =>
  z.object({
    val: z.number(),
    a: A,
  }),
);

const a: any = { val: 1 };
const b: any = { val: 2 };
a.b = b;
b.a = a;

const parsedA = A.parse(a);
const maskedA = A.mask({ val: true, b: { val: true, a: { val: true } } }, parsedA);
```

`.mask` isn't actually implemented yet, I was just toying with the idea. Would this work for your use cases? I'll leave this issue open in the meantime

**Comment by christophemarois** [comment]
This looks and feels very right. There aren't many ways to achieve this particular result at the moment. 

Your `.mask` idea makes me think of it like a “graphQL for native TypeScript”, by which I mean: a system where a data structure can be type-checked and deeply picked across relations.

In your `mask` sketch, how would you see one-to-many relationships, such as `array(object({}))`?

**Comment by vriad** [comment]
Funny you say that! I'm working on a GraphQL query builder right now :) It'll have similar syntax to the query builder in [mst-gql](https://github.com/mobxjs/mst-gql) but that lib doesn't actually generate a custom type for each query, it just returns the full data type of the model being fetched. They have a whole [section of the readme](https://github.com/mobxjs/mst-gql#dealing-with-incomplete-objects) about that limitation...why not just fix it? 🙄

For one-to-many relations, I presume the mask would just be applied on each element of the array.

```ts
const Player = z.object({
  inventory: z.array(z.object({
    name:z.string(),
    quantity: z.number()
  }))
});

const player = Player.parse({
  inventory: [{ name: "Sword", quantity: 1 }]
});

const inventoryMask = Player.mask({ inventory: { name: true } }, player);
// => { inventory: [{ name: "Sword" }] }
```

This feels "GraphQL-ey" since GraphQL queries look the same regardless of whether a relation is toOne and toMany.

**Comment by vriad** [comment]
Closing this for now, since the original issue has been resolved.

To summarize, Zod does not allow any unknown keys by default. If you have an object schema and want to allow unknown keys when parsing, use `schema.nonstrict()`. This is documented here: https://github.com/vriad/zod#unknown-keys

**Comment by vriad** [comment]
@christophemarois I moved the discussion surrounding masking to #29
