### ISSUE TITLE
[Question] How do I validate fields after calling .transform?

### ISSUE THREAD

**Issue by marlonbernardes** [vriad/zod#160]
Hi!
First of all, thanks for creating this great library. 
I'm giving `zod@beta` a try (more precisely, `v2.0.0-beta.5`), as I'm especially interested in the `transform` feature.

Now to the question. Let's assume I have the following object:

```ts
const query = {
  // note that the values below are strings, not numbers
  size: '10',
  offset: '20'
};
```

**What I want to do:**
 - convert the strings above to numbers
 - validate that these numbers are greater than 1

Is there a way of achieving this using a single schema and a combination`.min(1) and .transform()?`

Let's assume that the query object is constructed from an external source and I cannot change the values of the fields size or offset to be numbers.

 Unfortunately the code below won't work, as `.transform` returns a `ZodTransformer`
 which has no method called .min().

### Attempt 1 (does not work)

```ts
const schema = z.object({
  size: z.string()
    .transform(z.number(), Number)
    // unfortunately this won't work - as ZodTransformer does not have a method called .min()
    .min(1)
})
```

### Approach 2 (works with some downsides)

```ts
const schema = z.object({
  size: z.string()
    .refine(val => Number(val) > 0)
    .transform(z.number(), Number),
  offset: z.string()
    .refine(val => Number(val) > 0)
    .transform(z.number(), Number),
})
```

The approach above works, but there are a couple downsides:
  - I'm transforming a string to a number twice (one time inside `.refine` and one time inside `.transform`)
  - I can't leverage of the API returned by `z.number()` which is more elegant than refine and also returns more specific error codes.

This can probably also be solved by using two different schemas, but that would introduce a bit of duplication which I would like to avoid.

Is there a way of achieving what I want to do while using a syntax more similar to the first approach? 

Thanks in advance - happy to give more details if needed.

**Comment by tmtron** [comment]
I think you should add the tests directly to the output type:

```ts
z.object({
      size: z.string().transform(z.number().min(1), Number)
    });
```

**Comment by marlonbernardes** [comment]
@tmtron thanks! Not sure how I missed it. This is certainly more elegant than the .refine solution. Closing this issue.

**Comment by vriad** [comment]
Thanks again @tmtron !
