### ISSUE TITLE
Zod 2 beta 5: applying transform() to arrays 

### ISSUE THREAD

**Issue by grreeenn** [vriad/zod#166]
Hi,

I'm trying to use `.transform()` on a string array to remove possible duplicates.
This is my schema:
```ts
DummyInput = z.object({
  pokemonTypes:
    z.array(string())
    .nonempty()
    .transform(cleanDuplicateStringsFromArray)
})
```
The function signature is `(array: string[]) => string[]`. Seems right - take an array of strings and transform it to itself.. although I get an error: 
```
TS2345: Argument of type '(array: string[]) => string[]' is not assignable to parameter of type '(arg: [string, ...string[]]) => string | Promise<string>'.   Type 'string[]' is not assignable to type 'string | Promise<string>'.     Type 'string[]' is not assignable to type 'string'.
```

Am I missing something here?

**Comment by tmtron** [comment]
nice you call `.nonempty()` your input type is not just a `string[]`, but `string, ...string[]`.

so your transformer function could be like this:

```ts
function cleanDuplicateStringsFromArray(arg: [string, ...string[]]) {
  return arg;
}
```

**Comment by grreeenn** [comment]
So basically I can't write a generic method to check duplicates in nonempty and possibly empty arrays.

Solved it with a custom `.refine(validateNonEmptyArray)` after the transformer. Ideally, there should be a way to call `.nonempty()` after the transformer (now it's `TS2339: Property 'nonempty' does not exist on type 'ZodTransformer   >, ZodArray  >>'.`), but I understand this solution might prove overly complex.

Thanks @tmtron!

**Comment by tmtron** [comment]
@grreeenn maybe you only want to call `min(1)` instead of  `nonempty()`. Then the type will remain `string[]`, but zod will still validate that there is at least one item:

```ts
function uniqueStringsInArray(arg: string[]) {
  // get an array of distinct items
  const distinctItems = [...new Set(arg)];
  return distinctItems;
}

const DummyInput = z.object({
  pokemonTypes:
    z.array(z.string())
    .min(1)
    .transform(uniqueStringsInArray)
})


```

**Comment by grreeenn** [comment]
Didn't realize that there's a difference between the two. It worked, thanks again!

**Comment by vriad** [comment]
Thanks @tmtron!

@grreeenn there probably shouldn't be a difference but I guess it worked out in your case. If anyone else is unhappy with the typing of .nonempty feel free to implement your own validation logic with `.refine` (which never changes the inferred type).
