### ISSUE TITLE
[Discussion] Parsing input that's a superset of the schema type

### ISSUE THREAD

**Issue by pjdon** [vriad/zod#169]
Given a zod schema like
```
const ZRecord = z.object({
    id: z.number(),
    name: z.string()
});
```
how can I use `ZRecord` to extract the schema from a conforming object that has additional fields? E.g.
```
const result = ZRecord.safeParse({ id: 123, name: "Joe", notes:"enjoys hiking" });
```

Is there any option that I can pass to the parse methods (e.g. `ZRecord.safeParse`) that will ignore additional keys, but also mention them in the `result.error.errors` list? I was hoping that even when `result.success` was `false`, `result.data` would still have the parsed hierarchy. I don't see a way to do this other than iterating through the `ZAddEntryParams.shape` hierarchy and pulling the relevant attributes from the input into a new "clipped" object before parsing.

It would be valuable to extract the schema from a larger object for something like a web request, to give the API caller a message that they had extra keys in their request.

**Comment by vriad** [comment]
Nope, not planning to support this.

**Comment by pjdon** [comment]
> Nope, not planning to support this.

It's a feature in Zod 2, I just missed the link at the top of the main README

https://github.com/vriad/zod/tree/v2#unknown-keys

**Comment by vriad** [comment]
Hm maybe I misunderstood what you meant but this is not something Zod does:

> ignore additional keys, but also mention them in the result.error.errors list

**Comment by pjdon** [comment]
Oh I see, that was just a secondary thing. I kinda merged the two questions into one and it wasn't clear.

Thanks for making this library. The more I use it the more I'm impressed with how complete and well conceived it is.

**Comment by vriad** [comment]
Thank you! That's always great to hear :)
