### ISSUE TITLE
How to check if an object "isZodSchema"?

### ISSUE THREAD

**Issue by SrBrahma** [vriad/zod#170]
Hey!

I am updating one package of mine, and it would always accept an object containing zod shapes, like

```ts
const zodShape = {
  value: zod.number()
}
function f<Z extends ZodRawShape>(zodShape: Z) {
  const schema = zod.object(zodShape)
}

```

I was doing it to prevent having to always write zod.object({...}), as I was using always objects.

However, now I want it to also accept stuff like a zod.number() without a wrapping object, but still being able to pass an object without the wrapping zod.object() (will be applied automatically by the function).

So, I need to check if the object is already a zod schema so I don't run z.object() on a it again.

Is there some kind of isZodSchema function?

**Comment by vriad** [comment]
All ZodSchemas are a instance of z.Schema so this should work:

```ts
zodShape instanceof z.Schema<any>;
```

But this looks like a bad practice in general. I don't recommend passing around ZodRawShapes like this, it just overcomplicatess the logic unnecesarily.

**Comment by Carlo-Codes** [comment]
is this still possible? I am using v4 and I am trying to check if a property is an object to no avail - everything, even nested objects are treated as not an instanceof ZodObject  ```	const shape = schema.partial().shape;

	const baseSchemaShape: Record<string, ZodType> = {};

	for (const key in shape) {
		const val = shape[key];
		if (val instanceof ZodObject) {
			baseSchemaShape[key] = z.lazy(() => buildRootWhereSchema(val)).optional();
		} else {
			baseSchemaShape[key] = colOps(val as ZodType);
		}
	}

**Comment by Carlo-Codes** [comment]
is this still possible? I am using v4 and I am trying to check if a property is an object to no avail - everything, even nested objects are treated as not an instanceof ZodObject  ```	const shape = schema.partial().shape;

	const baseSchemaShape: Record<string, ZodType> = {};

	for (const key in shape) {
		const val = shape[key];
		if (val instanceof ZodObject) {
			baseSchemaShape[key] = z.lazy(() => buildRootWhereSchema(val)).optional();
		} else {
			baseSchemaShape[key] = colOps(val as ZodType);
		}
	}
