### ISSUE TITLE
In V2 how to get `parseAsync` to collect errors for all fields?

### ISSUE THREAD

**Issue by ntilwalli** [vriad/zod#174]
Firstly, thanks for this great lib! I'm wondering how to collect errors for all fields in the new `parseAsync` method?  It seems to stop collecting after the first error.
```
import * as z from 'zod'

const schema = z.object({
  username: z.string().nonempty(),
  password: z.string().nonempty(),
});

schema.parseAsync({username: '', password: ''})
  .then(() => {})
  .catch(e => {
    if (e.errors.length !== 2) {
      throw 'Expected two errors'
    }
  })
```

**Comment by vriad** [comment]
The `errors` property on ZodErrors has been renamed to `issues` to avoid inconsistency in the usage of the term "error". Previously ZodErrors contained multiple "suberrors" but the property containing was called "errors" and it was the source of a lot of confusion 👍
