### ISSUE TITLE
Type 'ZodTransformer<ZodAny, ZodBoolean>' is not assignable to type 'ZodTypeAny'

### ISSUE THREAD

**Issue by agentlewis** [vriad/zod#176]
Is this error meant to be correct? If so I feel like I just missed something fundamental in how to use transforms.

I am using the transforms I created in [pip-types](https://github.com/bamboocreativenz/pip-types/blob/8918d7721383aaac5a39ea07b88077db244b4bdc/src/boolean.ts#L120), though in the new project I updated zod to `"zod": "^2.0.0-beta.9"` and can compile and run the tests.

The code: 

```
export const surveyRecordTransform = z.object({
  name: z.string(),
  archive: zToBoolean,
  ... (100 more such lines)
})
```

I would then use this:

```
const typedSurveyRecord = surveyRecord.parse(data)
```

And i get this error (from VSCode type checking)

```shell
(property) Archive: ZodTransformer<ZodAny, ZodBoolean>
Type 'ZodTransformer<ZodAny, ZodBoolean>' is not assignable to type 'ZodTypeAny'.
```

<details>
<summary>Rest of error :)</summary>

```
  Types of property 'parse' are incompatible.
    Type '(x: unknown, params?: ParseParams) => boolean' is not assignable to type '(x: unknown, params?: ParseParams) => any'.
      Types of parameters 'params' and 'params' are incompatible.
        Type 'import("...node_modules/zod/lib/src/parser").ParseParams' is not assignable to type 'import("...node_modules/zod/lib/src/parser").ParseParams'.
          Types of property 'seen' are incompatible.
            Type '{ schema: any; objects: { data: any; error?: any; times: number; }[]; }[]' is not assignable to type '{ schema: ZodType<any, ZodTypeDef, any>; objects: { input: any; error?: ZodError; output: any; }[]; }[]'.
              Type '{ schema: any; objects: { data: any; error?: any; times: number; }[]; }' is not assignable to type '{ schema: ZodType<any, ZodTypeDef, any>; objects: { input: any; error?: ZodError; output: any; }[]; }'.
                Types of property 'objects' are incompatible.
                  Type '{ data: any; error?: any; times: number; }[]' is not assignable to type '{ input: any; error?: ZodError; output: any; }[]'.
                    Type '{ data: any; error?: any; times: number; }' is missing the following properties from type '{ input: any; error?: ZodError; output: any; }': input, outputts(2322)
base.d.ts(29, 5): The expected type comes from this index signature.
```

</details>

I do realise that I am trying to compose my transform within another Zod object and thinking about this now I realise this may not have been how I am meant to use it.

ie make a bunch of coercion transforms and then use these in Zod Objects to then use on incoming Api data to both map and coerce the types and provide static typing for development... AND very LOUD errors should the coercion fail. #my-little-dream

**Comment by vriad** [comment]
Looks like you're trying to mix-and-match schemas from Zod 1 (in pip-types) and Zod 2 (in your application code), which is causing the error. You'll have to upgrade `pip-types` to Zod 2 as well for compatibility.

**Comment by agentlewis** [comment]
Hmm pip-types is some old code. I moved to using a monorepo and thought upgraded there. But all good if thats the likely culprit I'll work it out. 🙏
