### ISSUE TITLE
[Request] Generate JSON schema out of a zod object

### ISSUE THREAD

**Issue by cybervaldez** [vriad/zod#177]
@tonyxiao that's exactly what I am looking for because basically:
- all my backend services use `fastify` (rest framework like Express)
- each route has a JSON Validator built-in
- each backend service exposes its OpenAPI Spec thanks to these json schemas

So basically, I am looking at a Zod to JSON Schema helper to avoid having to double specify each type. Let me know if you find anything!

_Originally posted by @lazharichir in https://github.com/vriad/zod/issues/75#issuecomment-694865003_

**Comment by vriad** [comment]
This is possible but out of scope for Zod core, in my opinion. I don't want to be responsible for maintaining a bunch of "generate X from Zod" utilities. If you want to implement this I recommend looking at the parser (`src/parser.ts`) as a starting point. It's really just a recursive function containing a giant `switch` statement for all the possible subclasses of ZodType. In Zod 2 all schemas also have utility functions `isOptional` and `isNullable` which may help with this.

**Comment by StefanTerdell** [comment]
@cybervaldez I've started poking at this. Results are here: https://www.npmjs.com/package/zod-to-json-schema

Still _very_ early but might be useful to fork or PR if you need something specific.
