### ISSUE TITLE
z.string() satisfied with empty string in ^2.0.0-beta.9

### ISSUE THREAD

**Issue by johnnypea** [vriad/zod#182]
^2.0.0-beta.9

Tested with `z.string().parse("")` as well.

I don't suppose this is the expected behaviour?

**Comment by johnnypea** [comment]
Or should I use `z.string()nonempty()` ? It seems to work, but it is nowhere in docs.

**Comment by lazharichir** [comment]
I would think that's actually the expected behavior as an empty string `""` is a `string` and you can use `nonempty()` or `min(n)` for further refinement?

**Comment by vriad** [comment]
Thanks @lazharichir !

@johnnypea Oops guess I forgot to document this. Thanks for pointing that out!
