### ISSUE TITLE
catchall doesn't work in 2.0.0-beta.9

### ISSUE THREAD

**Issue by yunyu** [vriad/zod#184]
The example for `.catchall` in the readme doesn't return the correct result:

```ts
> z.object({name: z.string()}).catchall(z.number()).parse({name: "Foo", validExtraKey: 61})
{ name: 'Foo' }
```

It should have returned:

```ts
{name: 'Foo', validExtraKey: 61}
```

**Comment by vriad** [comment]
Thanks for pointing this out! Very dumb bug indeed. Fixed in zod@2.0.0-beta.12.
