### ISSUE TITLE
type infer of schema.default() not optional automatically?

### ISSUE THREAD

**Issue by xiaoyu-tamu** [vriad/zod#188]
![image](https://user-images.githubusercontent.com/33362998/95657702-80cd8400-0adb-11eb-91fd-cab5a52e4265.png)

> Equivalently you can express this using the built-in .default() method, available on all Zod schemas. The default value will be used if and only if the schema is undefined.

Should schema be optional when default is defined?

**Comment by tmtron** [comment]
you want to use `z.input<typeof Input>;` instead of `z.infer` which is the same as z`.output`

**Comment by xiaoyu-tamu** [comment]
@tmtron Thanks
