### ISSUE TITLE
vs Yup

### ISSUE THREAD

**Issue by lishine** [vriad/zod#19]
Hi,

I have read your article and reasoning for creating this lib. And I first, ye cool correct types, I will use it.
But then I see that
1. Is a fraction of yup features
2. json-schema could be converted to yup
3. With yup I can insert custom messages
4. I can do required('this is required')

My question, where do you use it, so you can live without the above features?

**Comment by vriad** [comment]
To address your points in order:

1. Zod is definitely missing lots of validation checks that Yup has. For instance, `yup.number().positive()`.  For Zod's v1, I was only concerned with representing/validating types with an equivalent representation in TypeScript's type system. There is no way to represent a "positive number" type in TypeScript. But I certainly intend to implement a wider array of validators down the road. 

2. Not interested in this - the point of something like Zod is to avoid dealing with JSON-based schema declarations and their associated fragile codegen-based ecosystems.

3. I like the custom messages concept from Yup. The API of Zod is flexible enough to support something like this in the future. I'll add it to the list.

4. Seems like a subset of #3. 

None of these strike me as particularly vital features. I'm using Zod in production on a commercial project, and it gets the job done. 🤷‍♂️
