### ISSUE TITLE
Missing type for discriminated union result of safeParse

### ISSUE THREAD

**Issue by instantepiphany** [vriad/zod#191]
Maybe I am doing something incorrectly here.

If I have an array of results from `safeParse`, and I want to filter on the successful ones and then use the `data` from each, I need a type to pass to the `Array.filter` function. Zod does not export a type like this, because the appropriate type is only defined inline: 
https://github.com/vriad/zod/blob/d1ae8e3538167a41e13ab6cfc2466ef3ca69e63a/src/types/base.ts#L69

I defined a type that takes the `typeof` of a schema as input, and can then be passed to `.filter` to allow this behavior.

The type is:
```
type ZodSafeParseSuccess<T extends zod.ZodSchema<T['_input']>> = { success: true; data: zod.infer<T> };
```
And assuming `parseResult` is the output of calling `safeParse` on an input (say objects retrieved from a database or sent by a client), here is example usage:
```
  [parseResult]
    .filter(
      (result): result is ZodSafeParseSuccess<typeof someSchema> => result.success === true,
    )
    .map((result) => result.data);
```

Here, in the `.map` tsc will know that `data` exists and infer its type correctly based on the schema. 

An appropriate `ZodSafeParseError` type could easily be derived similarly.

Looking forward to feedback - was there an easier way to do this, or should this be closed as a reference for how to fix, or should I open a PR and add this type definition into Zod?

**Comment by vriad** [comment]
I see what you're trying to do. I recommend using TypeScript utilities to "extract" the type.

```ts
const schema = await z.object({ name: z.string() }).catchall(z.number());
type schemaResult = ReturnType<typeof schema['safeParse']>;
```

I find this cleaner than exporting a bunch of utilities like `ZodSafeParseSuccess`. This is a fairly advanced/niche use case so I don't think I'll add this to the docs - they're cluttered enough already 👍

**Comment by instantepiphany** [comment]
Thanks, I didn't think of using `ReturnType`!
