### ISSUE TITLE
v2.0.0-beta.12: Cannot find module <...>/node_modules/zod/[]]./lib/src/index.js'.

### ISSUE THREAD

**Issue by marlonbernardes** [vriad/zod#192]
After upgrading to `v2.0.0-beta.12` I started getting the following error:

```
Cannot find module <...>/node_modules/zod/[]]./lib/src/index.js'.
```

Caused by this line:
https://github.com/vriad/zod/blob/v2/package.json#L5

It seems that the main field in the package.json file was very recently changed from:

```
"main": "./lib/src/index.js",
```
to

```
"main": "[]]./lib/src/index.js",
```

**Comment by vriad** [comment]
Fixed by #193 - it was an accident, my bad!
