### ISSUE TITLE
z.infer not required by default?

### ISSUE THREAD

**Issue by ralphilius** [vriad/zod#194]
![image](https://user-images.githubusercontent.com/4253551/96373779-e20aec80-1198-11eb-87e6-61b065330b77.png)

I'm using Typescript 4.0.3 and zod 1.11.9

**Comment by vriad** [comment]
This happens when you don't have `"strictNullChecks": true` in your tsconfig.json.

<img width="885" alt="Screen Shot 2020-10-18 at 8 51 04 PM" src="https://user-images.githubusercontent.com/3084745/96390652-a580c600-1183-11eb-9025-eb784013d3f8.png">

**Comment by ralphilius** [comment]
@vriad It doesn't work. Do I need to recompile or something? I run `next dev` command after making changes.

**Comment by vriad** [comment]
Make sure you save the new `tsconfig.json`. You can also try restarting the TS server if you're using VSCode: https://stackoverflow.com/questions/47700939/how-to-reset-intellisense-in-vs-code/55212141#:~:text=Restart%20the%20TypeScript%20language%20service,restart%22%20and%20it%20should%20autosuggest)

If that doesn't work paste your tsconfig here
