### ISSUE TITLE
Type assertions

### ISSUE THREAD

**Issue by m-rutter** [vriad/zod#2]
I've been thinking a lot about validation libaries and I share your frustration with Yup. Yup does not get everything right. I'm scared about to introducing io-ts is it has a high a cognitive overhead, but I really love what io-ts does.

I think I'll experiment with this libarary a bit, but in terms of io-ts features do you think zod could be improve with these features?

* built in type guards - i.e.  io-ts's `is()` method on codecs.
* built in type assertions - (maybe call it `assert()`) using the new assertion function types in typescript 3.7 (io-ts doesn't actually have this probably because it wants us to use `Either` instead of exceptions)
* branded types - doing io-ts's symbol trickery to create types like `NonZeroNumber` or `Email` 
  * it might be difficult to do that one while remaining ergonomic

**Comment by vriad** [comment]
Just implemented type guards and published it to `zod 1.0.5`. I'm using `io-ts`'s same `.is()` API. That was an easy one :)

Tried to implement type assertions as well but it looks like it's [not possible](https://github.com/microsoft/TypeScript/issues/34596) to do that yet without requiring duplicative typings :/ We'll have to wait and see on that.

I'm going to leave this issue open for now until I figure out an approach for doing branded types and string validators. I don't love all the boilerplate associated with `io-ts` branded types (i.e. `interface PositiveBrand { readonly Positive: unique symbol }`). I may be able to include validators as a literal generic argument of the ZodString/ZodNumber class, like so:

```
const num: z.number({ max: 5 }) // => z.ZodString
const max5: z.number({ max: 5 }) // => z.ZodString<{ max: 5 }>
```

 But I need to investigate that more deeply.

**Comment by vriad** [comment]
For future reference, the `.is()` method has been replaced by `.check()`. `.is()` will still work until the release of zod@2 but it should be considered deprecated.

I'm closing this, since type assertions [don't appear to work](https://github.com/microsoft/TypeScript/issues/34596) currently for generic classes such as ZodType. If this changes in the future I'll look into it again. And of course if someone cleverer than me figures out how to make assertions work, PRs are welcome!

**Comment by ceefour** [comment]
https://www.npmjs.com/package/typed-assert mentions:

> Consider using [zod](https://github.com/colinhacks/zod)
> While this library does a fine job for most simple use cases, please consider using [zod](https://github.com/colinhacks/zod) if you need more complex assertions.

It doesn't seem that zod is able to perform TypeScript 3.7 assertions the way `typed-assert` does it.
I've tried using `.parse()` and the checked value is still "not asserted (at compile-time)".
