### ISSUE TITLE
Include src in compiled package

### ISSUE THREAD

**Issue by okhomenko** [vriad/zod#20]
My webpack throwing a lot of warnings about sourcemaps.
```
WARNING in ./node_modules/zod/lib/types/string.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file '../../src/types/string.ts': Error: Can't resolve '../../src/types/string.ts' in '/Users/okhomenko/brightback/brightback-server/src/main/webpack/node_modules/zod/lib/types'

WARNING in ./node_modules/zod/lib/types/object.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file '../../src/types/object.ts': Error: Can't resolve '../../src/types/object.ts' in '/Users/okhomenko/brightback/brightback-server/src/main/webpack/node_modules/zod/lib/types'
```

It's trying to merge sourcemaps from zod and can't find source typescript files.
@vriad Could you please include src as part of the published package?

**Comment by vriad** [comment]
It causes issues in other people's builds if the source is included with the package. 

Based on a quick search you can solve your issue by excluding `node_modules` from their `source-maps-loader` plugin. Link: https://github.com/apollographql/react-apollo/issues/597#issuecomment-306091791

Let me know if that works, closing in the meantime. 👍
