### ISSUE TITLE
protected _refinement field in ZodType breaks cross package schema usage

### ISSUE THREAD

**Issue by guigzzz** [vriad/zod#202]
- package A (has dependency on zod)
```ts
import * as z from 'zod';

export const s = z.object({
    id: z.string(),
});
```
- package B (also has dependency on zod)
```ts
import { s } from 'package A';
import * as z from 'zod';

const makeValidator = <T>(schema: z.ZodType<T>) => {
    return (thing) => schema.safeParse(thing);
};

export const validator = makeValidator(s); // line 26
```
- error on `line 26`:
```
Property '_refinement' is protected but type 'ZodType<Type, Def>' is not a class derived from 'ZodType<Type, Def>'
```

I think this issue is caused by this typescript limitation https://github.com/microsoft/TypeScript/issues/7755

I have found the following workaround to get structural typing to work again
```ts
type SafeParseResult<T> =
    | {
          success: true;
          data: T;
      }
    | {
          success: false;
          error: z.ZodError;
      };

interface ZodParser<T> {
    safeParse(thing: unknown): SafeParseResult<T>;
}

const makeValidator = <T>(schema: ZodParser<T>) => {
    return (thing) => schema.safeParse(thing);
};

export const validator = makeValidator(s); // ok
```

Another workaround is to have package A declare a peerDependency on `zod`, but that's  a pain.

A nice solution would be to export an interface to make working with schemas in a generic fashion easier. I think schemas should all implement a unique interface, similar to ZodType<T> but without the protected/private components.

**Comment by vriad** [comment]
I just removed the `protected` status from `_refinement_`. If you upgrade both to zod@1.11.10 or later everything should work. Might not be the best practice here but ain't nobody got time for that. 

Thanks for pointing out this issue 🤙
