### ISSUE TITLE
[Feature request] make it possible to access the form data when creating custom error messages

### ISSUE THREAD

**Issue by Eddie-CooRo** [vriad/zod#203]
I believe we have an issue that is similar to !163, but, I'm not sure if our issue can be addressed using the `refinementData`.

Consider having the following schema:
```ts
z.object({
  paymentType: z.object({
    name: z.string(),
    minLimit: z.number(),
    maxLimit: z.number(),
  }),
  amount: z.number()
})
```
So the amount should always stay between minLimit and maxLimit. we can check for this simply by using a `.refine`:
```ts
z.object({...})
  .refine(
    ({ paymentType, amount }) => paymentType <= amount.maxLimit,
    { message: "Please enter a smaller value", path: ["amount"] }
  )
  .refine(
    ({ paymentType, amount }) => paymentType >= amount.minLimit,
    { message: "Please enter a larger value", path: ["amount"] }
  )
```
This works perfectly fine, but the issue arises when I want to show a more descriptive error message. something like ```The value should be greater than or equal to ${paymentType.min}```.
It's simply not possible to handle this case in the schema itself, and I need to refine the schema afterward in my component when I have the selected values in a state (I'm using `React`).

My proposal is to add support for passing a function as the `refine`s second parameter with the following definition:
```ts
(arg: Type) => Pick<Check<Type>, "path" | "message" | "params">
```
So we can have access to everything we need when we're constructing the error message.

I also thought about changing the refine signature to something like this:
```ts
refine: <Func extends (arg: Type) => any>(check: Func, message?: string | Pick<Check<Type>, "path" | "message" | "params">) => this;
refine: <Func extends (arg: Type) => any>(check: (arg: Type) => { isValid: boolean } & Pick<Check<Type>, "path" | "message" | "params">) => this;
```
It's much simpler, but as we are letting `any` as the return type of the check func right now, this would be a breaking change that we might want to avoid. So I propose accepting a function as the second parameter at least.

**Comment by vriad** [comment]
Check out the `_refinement()` method. It's a far more powerful method for cases like this. `.refine` delegates to it — check out its implementation in `base.ts`. It gives you the ability to add arbitrary refinement logic and throw multiple issues of any type (not just `ZodCustomIssue`).
