### ISSUE TITLE
V2 - Readd checks info on schema

### ISSUE THREAD

**Issue by julianomqs** [vriad/zod#207]
Hello,

I'm implementing a functionality to add **maxLength** attributes in input fields in React, based on the value of max attributes of Zod schema.

Basically, I read every field of schema, and check the **._def.checks** and pick up the **maximum** attribute of **too_big** code.

The **checks** was an array of objects in version 1, with the **code**, **maximum** and another info.

But in version 2 the **checks** array is an array of objects with only a check property with a function.

Would it be possible to add those information again?

**Comment by vriad** [comment]
This duplicates https://github.com/vriad/zod/issues/163 so I'm gonna close
