### ISSUE TITLE
Is it possible to generate schema from ts annotation using babel plugin?

### ISSUE THREAD

**Issue by linonetwo** [vriad/zod#21]
Just like how https://github.com/gcanti/babel-plugin-tcomb works.

**Comment by vriad** [comment]
This is definitely out of my wheelhouse, and if I (or anyone else) got around to it, I expect it would be implemented as a standalone library. 

Personally, I built Zod so I don't have to ever defining TypeScript types again so I doubt I'll get around to this anytime soon 😅

**Comment by linonetwo** [comment]
I think you are right since we can use the schema as ts types, we don't need to use type as schema...

I thought the reason why babel-plugin-tcomb exists is that flowtype can't do so.
