### ISSUE TITLE
How to define two objects that depends on each other (circular references)?

### ISSUE THREAD

**Issue by JVictorV** [vriad/zod#212]
In typescript youre able to create two types that depends in each other, ex:

```ts
type ObjectA = {
  b: ObjectB;
};

type ObjectB = {
  a: ObjectA;
};
```
But a similar pattern doesn't work with zod
```ts
const zObjectA = z.object({
  b: zObjectB,
});

const zObjectB = z.object({
  a: zObjectA,
});
```
`- error TS7022: 'zObjectA' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.`

**Comment by vriad** [comment]
Huh somehow this section got removed from the docs. Very weird...thanks for pointing this out! 🤔

https://github.com/vriad/zod#recursive-types
