### ISSUE TITLE
Can't use omit after calling transform

### ISSUE THREAD

**Issue by rossholdway** [vriad/zod#217]
Hi,

I've noticed that it's not possible to call `.transform` and then call `.omit`. Is this expected?

In the example below `const user` is invalid beacuse `omit` does not exist.

```typescript
export class Example {
  schema = zod.object({
    id: zod.number(),
    name: zod.string()
  }).transform((data) => data); //<-- just to illustrate the point

  create(name: string): zod.infer<Example['schema']> {
    const user = this.schema.omit({ id: true }).parse({ name });
    return this.db.save(user);
  }
}
```

**Comment by vriad** [comment]
Yes, this is expected. `.transform` returns an instance of `ZodTransformer`. You'd have a similar problem with `.optional` or `.nullable`.

**Comment by rossholdway** [comment]
@vriad Thanks for confirming. I've just discovered `.output` 🎉 , which allows me to do

```typescript
this.schema.output.omit({ id: true }).parse({ name });
```

I can't see much on this in the docs but assume this is part of it's intended use.

**Comment by vriad** [comment]
It is! I haven't documented it because it's currently "shallow" but I plan to re-implement it to recursively return the output schema from a tree of nested transformers. Shouldn't matter for your use case though 👍
