### ISSUE TITLE
Type guards vs Zod

### ISSUE THREAD

**Issue by PEZO19** [vriad/zod#23]
Hi!

I am wondering what are the differences between Zod and typescript type guards. What are the pros/cons/limits/purposes for each.

**Comment by vriad** [comment]
Zod's type guard function (`.check`) uses TypeScript type guards under the hood. 

Here's an example:
```ts
const mySchema = z.object({ hello: z.string() });
type mySchemaType = z.Infer<typeof mySchema>;
```

In this scenario, then the `mySchema.check()` method's type signature is `(u: unknown): u is mySchemaType`. This notation is described at https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards. Basically if you use a type guard in the clause of an if statement, TypeScript will now know the type of your variable in the body of the if statement:

```ts
const y: any = "whatever";
if(mySchema.check(y)){
  /// y is of type mySchemaType
}
```

It's also smart enough to figure out the opposite case, where you throw an error if a type check fails:
```ts
const y: any = "whatever";
if(!mySchema.check(y)) throw new Error("Invalid");

/// down here, y is of type `mySchemaType`
```
The type of a "type-guarded" variable in the if statement is *exactly* the type returned by `z.Typeof<typeof mySchema>`.

**Comment by nicholaschiang** [comment]
@colinhacks why did you remove these type guards in v3? It makes migrating from traditional TypeScript types and then separately defined type guards harder. For example, what used to be this:
```typescript
type Aspect = 'mentoring' | 'tutoring';
function isAspect(aspect: unknown): aspect is Aspect {
  return ['mentoring', 'tutoring'].includes(aspect as string);
}
...
const myAspects: Aspect[] = [];
if (isAspect(someRandomUnknownVariable)) myAspects.push(someRandomUnknownVariable);
```
Becomes a lot more verbose using `zod`'s new API:
```typescript
const myAspects: Aspect[] = [];
if (Aspect.safeParse(someRandomUnknownVariable).success) myAspects.push(Aspect.parse(someRandomUnknownVariable));
```
It would've been a lot easier if this type-guard feature still existed:
```typescript
const myAspects: Aspect[] = [];
if (Aspect.check(someRandomUnknownVariable)) myAspects.push(someRandomUnknownVariable);
```
Is there an easy way you could expose this API again (i.e. just by adding a `check` method that returns the same thing as `safeParse().success` but who's return signature is `someRandomUnknownVariable is Aspect`).

**Comment by scotttrinh** [comment]
@nicholaschiang 

The problem is that due to the fact that the input might have a completely different shape from the output, there isn't a safe way to have a type guard. Consider this example:

```ts
const querySchema = z.object({
  limit: z.string().transform(Number),
});

if (querySchema.check(request.query)) {
  needsNumber(request.query.limit); // Oops! this is a string!
}
```

In other words, `success` can only always be "correct" about the parsed/output value, not the input value.

It _is_ slightly more verbose, but this is how we deal with it:

```ts
const result = querySchema.safeParse(request.query);

if (result.success) {
  const { limit } = result.data;
  needsNumber(limit);
}
```

For our most common usage of checking API requests, we've even written a helper that is more like `parse` that returns a 400 response instead of throwing, so we can do things like:

```ts
const {
  query: { limit },
  body: { id },
} = parseRequest(response, bodySchema, request);

needsNumber(limit);
lookUpValueById(id);
```
