### ISSUE TITLE
Cannot find module 'zod'.

### ISSUE THREAD

**Issue by moltar** [vriad/zod#27]
My tests seem to be failing after the upgrade. Any ideas?

https://github.com/moltar/typescript-runtime-type-benchmarks/pull/155

https://github.com/moltar/typescript-runtime-type-benchmarks/pull/155/checks?check_run_id=553968076

**Comment by vriad** [comment]
Should be working now! Forgot to update package.json after switching up the project structure 😬 Thanks for notifying me 👍

**Comment by maietta** [comment]
I'm having the same problem. Works with no errors locally, but not in production. Using SvelteKit.
