### ISSUE TITLE
Dictionary type: unknown keys but known values

### ISSUE THREAD

**Issue by kingdaro** [vriad/zod#28]
I've looked through the docs, but I'm unclear on how to achieve a dictionary type that has unknown string keys, but known values, basically the type of `Record<string, KnownType | undefined>`. The `nostrict()` modifier is _close_, but I don't see how to specify the value type when using that

**Comment by vriad** [comment]
This is under development now, should be published by the end of the day

**Comment by vriad** [comment]
This has been published in zod@1.1.2.

The documentation is at https://github.com/vriad/zod#records.

Take it for a spin and let me know if you have any issues. Closing for now.
