### ISSUE TITLE
Parser logs to the console

### ISSUE THREAD

**Issue by hen-zone** [vriad/zod#31]
When using the library to parse values, I'm seeing a lot of logs to the console of this form:

    seen string before: undefined

They seem to be coming from this line in `parser.ts`: https://github.com/vriad/zod/blob/f154275fafd1cd105dcfe4bc63f37313057b3171/src/parser.ts#L24

Is this intended behaviour, or was this shipped by mistake?

**Comment by vriad** [comment]
Fixed in zod@1.2.1, sorry about that. Still working on a better logging system. 👍
