### ISSUE TITLE
Support for other primitives

### ISSUE THREAD

**Issue by ksmithut** [vriad/zod#35]
Are there plans to support other primitives such as Promise and BigInt?

**Comment by vriad** [comment]
I think it's a great idea - I'll look into this in the next couple days. Promise especially is important. The combination of function schemas and Promise types is gonna be 🔥

**Comment by vriad** [comment]
@ksmithut  Just implemented support for `bigint` and Promises in zod@1.3.0 

Take a look at the README to see how I'm handling Promises. Let me know if this approach works for your use case. 

What other primitive types would you want to see? If you think there are other types that should be implemented, I'll create additional issues for each of those. In the meantime, closing this.

**Comment by ksmithut** [comment]
That's awesome, love the promise approach you implemented. This will work wonderfully
