### ISSUE TITLE
Support for custom validation

### ISSUE THREAD

**Issue by pierreis** [vriad/zod#37]
Is there any plan to support custom validation?
It could be of the form: `z.string().validate(someValidationFunction)`.

That would be a great help to build advanced schemas.

This could also take the form of custom types, but for now, `z.ZodType` / `z.ZodTypeDef` not being exposed as part of the API make it a hack IMO.

**Comment by pierreis** [comment]
One way to perform this would be to add in a method in `ZodType` of the form:

```
validate(fn: Predicate<Type>, msg: ErrorMsg<Type>) => ZodType<Type, Def>
```

With:

```
type ErrorMsg<T> = string | ((obj: T) => string)
type Predicate<T> = (t: Type) => boolean
```

**Comment by vriad** [comment]
This is doable. I'm working on a big rewrite currently (probably gonna be Zoe 2) and I'll include this in that release.

**Comment by pierreis** [comment]
Sounds great. Do you need help in doing so?

**Comment by vriad** [comment]
The codebase is currently not fit for human eyes...

In the meantime I just implemented `.refine` which will let you accomplish this. Documented [here](https://github.com/vriad/zod#custom-validation). Give it a try and let me know if you have any issues. 👍

**Comment by jjhiggz** [comment]
I don't see it in the documentation for some reason, I'm wondering if this got added somewhere. 

I did this just to see if it would work and it did (I tested it with a length of 5).


````ts
const isValidPhoneNumber = (phonenumber: string) => phonenumber.length > 3

const SignupValidation = z.object({
  email: z.string().email(),
  cell: z
    .custom(isValidPhoneNumber, { message: "Not a valid phone number" })
    .transform((phoneNumber: string) => {
      return parsePhoneNumber(phoneNumber)
    }),
  
})
``` 

Obviously that's not a real phone validation, but the logic works for implementing a custom validation.

**Comment by slaesh** [comment]
so, is there something to add a "custom" validator which would then infer a "custom type" aswell?

imagine using zod in combination with prisma, having a JSONB field.. which should get a custom validation and should be properly typed for the app. :)

**Comment by slaesh** [comment]
probably found it: `z.custom<{ arg: string }>`
