### ISSUE TITLE
Add comparison to runtypes

### ISSUE THREAD

**Issue by greptail** [vriad/zod#4]
Hey @vriad, this package looks awesome. I am wondering (and I am sure other's who are reading the README) what the difference is between this package and [runtypes](https://github.com/pelotom/runtypes).

Would be great to add this info to the README as well!

**Comment by romainPrignon** [comment]
hey :)
Same case with https://github.com/sindresorhus/ow based on https://github.com/sindresorhus/is.

Would be great to have the full picture.
Anyway, great work ! love zod api

**Comment by vriad** [comment]
@gDelgado14 @romainPrignon  Working on these now. Trying to put together a comprehensive feature comparison table for all of the various TS libs.

**Comment by vriad** [comment]
Wrote up a short blurb comparing the two. At this point I'm fairly confident Zod is a superset of the functionality of runtypes with the exception of their "pattern matching" which lets you define operations over union types. Interesting idea but I'm not planning to support that at the moment - seems pretty niche.
