### ISSUE TITLE
JSON utility type

### ISSUE THREAD

**Issue by ggoodman** [vriad/zod#41]
I just found myself needing a generic type for any valid JSON and put this together:

```ts
type Literal = boolean | null | number | string;
type Json = Literal | { [key: string]: Json } | Json[];

const Literal = Zod.union([Zod.boolean(), Zod.null(), Zod.number(), Zod.string()]);
const Json: Zod.ZodType<Json> = Zod.lazy(() =>
  Zod.union([Literal, Zod.array(Json), Zod.record(Json)])
);
```

Putting this in an issue for anyone who might be on the lookout or if the library might want to integrate a higher-level utility constructs like this.

**Comment by vriad** [comment]
Love this! I'd add it to the standard API (`z.json()`) but the recursive type alias required TypeScript 3.7. Currently everything else in the lib only requires 3.2+ so I don't want to bump the version without a really compelling reason. But thanks for sharing!

**Comment by vriad** [comment]
@ggoodman decided to add this snippet to the README so it's easier to find 👍

**Comment by agentlewis** [comment]
Hey @ggoodman or @vriad, thanks for this helpful snippet.

I'm slowly getting more comfortable with Zod. But every now and then I feel like I am just missing the point of something.

Now is such a time.

When using this snippet with say `jsonSchema.parse(data)`

I get this in the log.

```shell

    types/util.ts:190:68 - error TS2693: 'Literal' only refers to a type, but is being used as a value here.

    190 export const jsonSchema: z.ZodSchema<Json> = z.lazy(() => z.union([Literal, z.array(Json), z.record(Json)]));
                                                                           ~~~~~~~
    types/util.ts:190:85 - error TS2693: 'Json' only refers to a type, but is being used as a value here.

    190 export const jsonSchema: z.ZodSchema<Json> = z.lazy(() => z.union([Literal, z.array(Json), z.record(Json)]));
                                                                                            ~~~~
    types/util.ts:190:101 - error TS2693: 'Json' only refers to a type, but is being used as a value here.

    190 export const jsonSchema: z.ZodSchema<Json> = z.lazy(() => z.union([Literal, z.array(Json), z.record(Json)]));
```

After trying to work this out I realised I am just playing whack a mole.

Any direction would be appreciated :)

**Comment by vriad** [comment]
Yikes! I renamed `JSON` in the snippet above to `jsonSchema` (to avoid name conflicts with the built-in `JSON` class) but I forgot to change it everywhere 😬  Here's the correct snippet:

```ts
type Literal = boolean | null | number | string;
type Json = Literal | { [key: string]: Json } | Json[];
const literalSchema = z.union([z.string(), z.number(), z.boolean(), z.null()]);
const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z.union([literalSchema, z.array(jsonSchema), z.record(jsonSchema)]),
);

jsonSchema.parse({
  // data
})
```
Thanks for pointing this out! I fixed this in the README as well.

**Comment by deini** [comment]
Now that the requirement is 4.1+, any chance `z.json()` gets revisited?

**Comment by bryantabaird** [comment]
Sharing here in case it will help somebody else, for our application, we had to change the `string` to be a `symbol` to handle some of our more complex types:

`type Json = Literal | { [key: symbol]: Json } | Json[];`

**Comment by BobToninho** [comment]
Hi, sorry for commenting an old issue.

Is there a particular reason to have `Literal` in the top level union? As `JSON.parse()` fails with strings ([link](https://www.typescriptlang.org/play/?#code/FIZQ8gcgdADghgJwM4FMAUByALipWMCUQA)), wouldn't something like this work more closely to the behaviour of the runtime?

```ts
const literalSchema = z.union([z.string(), z.number(), z.boolean(), z.null()]);
type Literal = z.infer<typeof literalSchema>;
type JsonValues = Literal | { [key: string]: JsonValues } | JsonValues[];
type Json = { [key: string]: JsonValues } | JsonValues[];
const jsonValuesSchema: z.ZodType<JsonValues> = z.lazy(() =>
  z.union([literalSchema, z.array(jsonValuesSchema), z.record(jsonValuesSchema)]),
);
const jsonSchema: z.ZodType<Json> = z.lazy(() => z.union([z.array(jsonValuesSchema), z.record(jsonValuesSchema)]));
```

Disclaimer: I am not familiar with the JSON spec, so I might be plain wrong here.

**Comment by paradoxloop** [comment]
Zod v4 now has an [inbuilt z.json() ](https://zod.dev/api?id=json) type.
