### ISSUE TITLE
Type inference incorrectly sets all fields as optional by default

### ISSUE THREAD

**Issue by pierreis** [vriad/zod#43]
Zod version: 1.5.0
TS version: 3.8.3

The type inference does not seem to be working properly, making all values of objects to be optional by default.

Let me take this code derived from the readme:

```ts
import * as z from "zod";

const dogSchema = z.object({
  name: z.string(),
  neutered: z.boolean(),
});

type T = z.TypeOf<typeof dogSchema>;  // -> { name?: string, neutered?: boolean }

const dog: T = {};  // -> Compiles without error
```

The expected behavior would be a compilation error deriving from `name` and `neutered` to be required.

**Comment by vriad** [comment]
You have to use Zod with strict mode. This wasn't clear from the README - my bad. Just add `"strict": true` in your tsconfig's "compilerOptions" and it'll work properly.

**Comment by mkreuzmayr** [comment]
Also be sure to **NOT** set `"strictNullChecks": false` in your `tsconfig.json`, because this would also result in all properties being infered as optional.

**Comment by mihanizm56** [comment]
strict and strictNullChecks both true
tsc in the project is 4.5.2
node 14.18
gatsby 4
zod: 3.11.6

also all fields are optional

**Comment by scotttrinh** [comment]
@mihanizm56 

Make sure your IDE or editor setup is properly getting your `tsconfig.json`, that's a common cause of that issue.

**Comment by bauti-defi** [comment]
strict and strictNullChecks both true
tsc in the project is 4.8.2
node 16.16.0
zod: 3.19.1

Using VScode. I have restarted the IDE multiple times. All my object field types are still being inferred as optional.

**Comment by KevinEdry** [comment]
> strict and strictNullChecks both true tsc in the project is 4.8.2 node 16.16.0 zod: 3.19.1
> 
> Using VScode. I have restarted the IDE multiple times. All my object field types are still being inferred as optional.
> 
> Edit: Seems to be VSCode problem...

how did you fix this?

**Comment by 0xacx** [comment]
I am having the same issue, tried all the suggestions: 
`"strict": true,
"strictNullChecks":true,
 "exactOptionalPropertyTypes": true,` 
 
 did not work for zod@npm:3.22.4.

**Comment by 0xacx** [comment]
I am having the same issue, tried all the suggestions: 
`"strict": true,
"strictNullChecks":true,
 "exactOptionalPropertyTypes": true,` 
 
 Did not work for zod@npm:3.22.4.

**Comment by imrim12** [comment]
Unfortunately adding more settings in tsconfig.json messes up my existing codebase
I wrapped `Required<>` around the inferred type to remove the optional modifiers

**Comment by skypesky** [comment]
This configuration is effective for me.

```json
{
  "compilerOptions": {
    "strict": true,
    "strictNullChecks": true
  }
}

```

**Comment by zcaceres** [comment]
Pretty bad experience. I wasted a long time fussing with Zod types until I found this thread. It's unintuitive behavior.
