### ISSUE TITLE
Type inference issue for Object schemas

### ISSUE THREAD

**Issue by cesar3030** [vriad/zod#45]
First, Thank you very much for your awesome work 👍 

I figured out when I'm using `z.infer` on an object schema, the inferred type has all the object's attributes optional. According to the doc, all the attributes should be required.

Example from the doc:
```typescript
const dogSchema = z.object({
  name: z.string(),
  neutered: z.boolean(),
});

type Dog = z.infer<typeof dogSchema>;

/* 
equivalent to:
type Dog = { 
  name:string; 
  neutered: boolean;
}
*/
```

But this is what I get:
```
type Dog = {
    name?: string;
    neutered?: boolean;
}
```

I'm using zod `1.5.0` and I've also tried with `1.3.0` but keep getting the Dog type with optional attributes.

Thanks for your help!

**Comment by vriad** [comment]
This happens when you aren't using Zod with `"strict": true` in your tsconfig. I recently (as in yesterday) added this clarification to the README [here](https://github.com/vriad/zod#typescript-versions) so you probably missed it.

**Comment by vriad** [comment]
Also - glad you like the library! Thanks for the kind words 🙂

**Comment by cesar3030** [comment]
Thank you very much for your very fast reply!!

**Comment by talmr-k** [comment]
Hi @vriad 

Also really loving Zod, but I am having the same issue.  Here's my tsconfig.json:

```
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "outDir": "dist",
    "allowSyntheticDefaultImports": true,
    "allowJs": true,
    "importHelpers": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "sourceMap": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitAny": false,
    "noImplicitThis": false,
    "strictNullChecks": true,
    "strict": true,
    "typeRoots": ["./typings", "node_modules/@types"]
  },
  "exclude": ["**/*.test.ts", "node_modules", "dist"]
}
```

I still get every field showing optional.  Am I doing something else wrong?

**Comment by vriad** [comment]
That's due to the `exclude` statement in your tsconfig. The`exclude` statement is used to exclude certain files from the TS configuration described in that `tsconfig.json`. So all your `**.test.ts` files are probably being analyzed using the default TS rules (which don't include `strict: true`). You'd have to add another tsconfig.json  (probably called `test.tsconfig.json` specifically for your test files or get rid of the `exclude`.

**Comment by vriad** [comment]
@talmr-k forgot to tag you. Here's a description on how to set up multiple tsconfigs: https://stackoverflow.com/questions/37579969/how-to-use-multiple-tsconfig-files-in-vs-code

**Comment by talmr-k** [comment]
Thanks so much @vriad 

Love this library and the support!
