### ISSUE TITLE
How to parse Dates in Api with zod

### ISSUE THREAD

**Issue by rbakaou** [vriad/zod#46]
Hi, Great wrok with zod. maybe i'm using it wrong but how would i parse a date in Api params i would get a string of Date and Zod expects a Date object. Should i  use the zod.string() and parse the date in the backend?

**Comment by vriad** [comment]
Yes, I'd recommend using a string field. If you want to verify that the string is, say, a valid ISO date string, then use a [custom validator ](https://github.com/vriad/zod#custom-validation) in combination with something like [validator.js](https://github.com/validatorjs/validator.js) to enforce that. 👍

**Comment by rbakaou** [comment]
Thanks Awesome
