### ISSUE TITLE
Middle Ground between strict and unstrict

### ISSUE THREAD

**Issue by blocka** [vriad/zod#51]
Often when calling an HTTP endpoint, we're only interested in small bits of the data, but not the whole response. I, therefore, tried to model a "zod" (don't know what you call it :) ) based on that shape. Of course, I got an error because of unexpected types. The docs pointed me to "nonstrict" mode, which works great. I have a guarantee that the properties I need are there. The only issue is that it's not typesafe...the "nonstrict" mode carries over to the other end, and I can ask for any property I want, even if it doesn't exist.

Is there a hybrid mode? Or perhaps a setting in parse that doesn't error when coming across unexpected properties.

**Comment by vriad** [comment]
@blocka Not sure I understand the problem. 

It's true that using `.nonstrict` expands the TypeScript definition to include `{[k:string]: any}` but you should still get proper autocomplete on the properties that you know to exist:

![Screen Shot 2020-05-16 at 4 09 27 PM](https://user-images.githubusercontent.com/3084745/82131999-f08b4d00-978f-11ea-886e-4a7f605d23a2.png)

Are you seeing that behavior?

If you want to strip all the unknown keys, I recommend using the approach I described [here](https://github.com/vriad/zod/issues/47#issuecomment-625474975)

Let me know if I'm not understanding something 👍

**Comment by blocka** [comment]
As I said that part works great. But I'm talking about accessing keys that don't exist. There is no error if I try to do that with nonstrict mode.

**Comment by vriad** [comment]
Gotcha. I don't plan to change this behavior. I want the inferred type of a `nonstrict` schema to behave like an interface, in that you can assign an object to it that includes unknown keys
```ts
const test = z.object({ asdf: z.string() }).nonstrict()
type test = z.infer<typeof test>;

const x: test = { asdf: "asdf", qwer: 1234 } // should work
```

There's no way to achieve this property and do what you're looking for. 

You could define the strict version of your schema, extract the type, then parse your API payload with the `nonstrict` version. It's slightly duplicative but still pretty nice:

```ts
const User = z.object({ username: z.string() });
type User = z.infer<typeof User>;

app.post('/', (req, res)=>{
  const user: User = User.nonstrict().parse(req.body);
})
```
