### ISSUE TITLE
proper mechanism to integrate with 3rd party types

### ISSUE THREAD

**Issue by cdaringe** [vriad/zod#52]
# problem

```ts
import { Bananas } from '@fruit/banana'
import * as z from 'zod'
const schema = z.object({
  apple: z.string(),
  banana: z.doSomethingWith3pType() // z.object({}) ??
})
const myType = z.infer<typeof schema> // { apple: string, banana: ???? }
```

what the best way to get my 3p schema in? assuming because types have been compiled away, getting my 3p schema may not be possible, _but_, is there a mechanism to put my type into the schema, and get it reflected back out?

**Comment by vriad** [comment]
I suppose I could implement a generic `z.external(...)` that accepts any object that conforms to a particular interface, probably this:

`interface Schema<T> {
  parse: (data:unknown): T;
  check: (data:unknown): data is T;
}`

What libraries are you trying to integrate with?

**Comment by cdaringe** [comment]
ATM im extending my schema with @types/puppeteer::Viewport. i have something like `{ url: string, viewport: Viewport }` 🤔

**Comment by vriad** [comment]
Ah so you're only interested in incorporating static types in your schemas, not doing runtime validation, correct?

You should just construct your own types using TypeScript's functionality:
```ts
const BaseType = z.object({ url: z.string() });
type BaseType = z.infer<typeof Test>;

type FinalType = BaseType & { viewport: Viewport };
 => { url: string; viewport: Viewport }
```

**Comment by vriad** [comment]
@cdaringe Just thought of a better way to do this!

```ts
const Viewport: z.ZodType<Viewport> = z.any();

const FullSchema = z.object({ url: z.string(), viewport: Viewport });
```

This way you can still run validations on everything without issue, since `z.any()` allows any inputs. 👍

**Comment by cdaringe** [comment]
Doh! I figured I was missing something! Perfecto, thx!
