### ISSUE TITLE
Require one of two fields

### ISSUE THREAD

**Issue by KolbySisk** [vriad/zod#61]
Similar to this Yup issue: https://github.com/jquense/yup/issues/176

I'd like to conditionally validate at least one of n values are set. Yup and Joi solve this problem with a `.when` method.

Does Zod currently have a solution to this problem?

**Comment by vriad** [comment]
The `when` method in Yup is really interesting, but super overkill for this scenario. I would implement this as a custom refinement/validator on the outer object:

```ts
const myObject = z
  .object({
    first: z.string(),
    second: z.string(),
  })
  .partial()
  .refine(
    data => !!data.first || !!data.second,
    'Either first or second should be filled in.',
  );
```

The `!!` is only required because the `refine` method expects a boolean to be returned. If you update to zod@1.6.2 I just pushed a change so any truthy value will pass a refinement check. This lets you have the slightly more readable version:

```ts
const myObject = z
  .object({
    first: z.string(),
    second: z.string(),
  })
  .partial()
  .refine(
    data => data.first || data.second,
    'Either first or second should be filled in.',
  );
```

Let me know if I misunderstood the scenario. 👍

So you could do

**Comment by KolbySisk** [comment]
Perfect - I was able to get this working. I had to define the refine twice though. I'm using `.merge` to create a new schema using the original with the refine, and had to add the same refine to the new schema. But it works great thank you.

I was looking at refine in the docs hoping it could solve my problem but didn't see any examples of using it on the zod object itself and not the properties. I'm already using refine a lot because of mui (going to open a new issue about this). 

Anyways, thanks for the help.

**Comment by vriad** [comment]
I'll try to clarify that the `refine` method is applicable to _all_ Zod schemas. I should probably rewrite everything in a more structured way, similar to Yup.

**Comment by vriad** [comment]
@KolbySisk thanks for pointing out the fact that you had to define the refinement twice. That was a bug. With zod@1.7 or later, if you `.merge` two object schemas, the result inherits the refinements of its parents (as it should be).

**Comment by maddijoyce** [comment]
To anyone coming across this issue looking for something similar to yup's when option, I wanted the error to appear on the field where the problem actually is not just at the top level as in @colinhacks example above and I thought I was at a dead end. I was wrong!

With the superRefine method, you can add a path to the addIssue call. E.g.

```
const myObject = z
  .object({
    first: z.string(),
    second: z.string(),
  })
  .partial()
  .superRefine((data, ctx) => {
     if (!data.first && !data.second) {
       ctx.addIssue({
         code: z.ZodIssueCode.custom,
         path: ["second"],
         message: "Second should be set if first isn't",
       });
     }
  });
```

**Comment by ckifer** [comment]
Feel the need to comment on this as I keep running into cases this is needed. 

I have large schema that needs to require one or another field. A nested partial Zod object with superRefine works for this (as shown above). 

What I want to be able to do however, is to do conditional requirement on 1 or 2 fields without making the entire object partial and while having access to all of the fields in the object. 

Ex:
I have a required enum that has two values: "ValueA" and "ValueB"

Upon "ValueA" then `someOtherFieldA` is required. Upon "ValueB" then `someOtherFieldB` is required. 

There are also other required fields within the schema that should remain required without explicitly checking them in something like `superRefine`. 

Is there any way to do this? Any plans for something like `.when` in Yup?

**Comment by DrBronsy** [comment]
> Feel the need to comment on this as I keep running into cases this is needed.
> 
> I have large schema that needs to require one or another field. A nested partial Zod object with superRefine works for this (as shown above).
> 
> What I want to be able to do however, is to do conditional requirement on 1 or 2 fields without making the entire object partial and while having access to all of the fields in the object.
> 
> Ex: I have a required enum that has two values: "ValueA" and "ValueB"
> 
> Upon "ValueA" then `someOtherFieldA` is required. Upon "ValueB" then `someOtherFieldB` is required.
> 
> There are also other required fields within the schema that should remain required without explicitly checking them in something like `superRefine`.
> 
> Is there any way to do this? Any plans for something like `.when` in Yup?

One month! Faster mtf!

**Comment by alex-udisc** [comment]
Can we reopen this issue? I don't think using super refine is a suitable solution for complex form validation. Making all fields optional and checking them in a superRefine function doesn't make sense for several use cases I'm currently working on. I think @ckifer summed up the issue perfectly.

**Comment by jrobeson** [comment]
I think it should be a new issue because the original issue as posted was solved.

**Comment by VIEWVIEWVIEW** [comment]
> 
> ```ts
> const myObject = z
>   .object({
>     first: z.string(),
>     second: z.string(),
>   })
>   .partial()
>   .refine(
>     data => data.first || data.second,
>     'Either first or second should be filled in.',
>   );
> ```

Hey @colinhacks, how would one make that work when I want to use this for more advanced strings?

For example, I have a registration form with three fields: ``username, email, password``.

Password is always required. *At least one of*  username or email should be required. 

I thought I could use a zod object as you described [here](https://github.com/colinhacks/zod/issues/61#issuecomment-639309093). However, that doesn't work when you add ``.email`` or ``.regex`` to the mix:
```ts
const schema = z
  .object({
    email: z.string().email().trim(),
    username: z.string().regex(/^[a-zA-Z_]+$/).trim(),
    password: z.string().min(8, { message: 'Password must be at least 8 characters' }),
  })
  .partial({
    email: true,
    username: true,
  })
  .refine(
    data => data.email || data.username,
    'Email or username required.',
  );
```

This one will still complain that an empty string "" is not a valid email / username, even when the other one is entered.

**Comment by VIEWVIEWVIEW** [comment]
I came up with a hack(?). It works, but it's not really beautiful imo:

```ts
const schema = z
  .object({
    email: z.string().email().trim(),
    username: z.string().regex(/^[a-zA-Z_]+$/).trim(),
    password: z.string().min(8, { message: 'Password must be at least 8 characters' }),
  })
  .or(
    z.object({
      username: z.string().regex(/^[a-zA-Z_]+$/).trim(),
      password: z.string().min(8, { message: 'Password must be at least 8 characters' }),
    })
  ).or(
    z.object({
      email: z.string().email().trim(),
      password: z.string().min(8, { message: 'Password must be at least 8 characters' }),
    })
  )
```

**Comment by mohamad-xtouch** [comment]
I solve my issue with this solution:

`
const FirstSchema = z.object({
  email: z.string().email(),
});

const SecondSchema = z.object({
  username: z.string().regex(/^[a-zA-Z_]+$/),
});

const MainSchema = z
  .object({
    password: z
      .string()
      .min(8, { message: 'Password must be at least 8 characters' }),
  })
  .merge(FirstSchema.partial())
  .merge(SecondSchema.partial())
  .superRefine((data, ctx) => {
    if (data.email) {
      const result = FirstSchema.safeParse(data);
      if (!result.success) {
        result.error.errors.forEach((issue) => ctx.addIssue(issue));
      }
    } else if (data.username) {
      const result = SecondSchema.safeParse(data);
      if (!result.success) {
        result.error.errors.forEach((issue) => ctx.addIssue(issue));
      }
    } else {
      ctx.addIssue({
        code: 'custom',
        path: ['username', 'email'],
        message: 'email or username is required',
      });
    }
  });`
  
  This is work if you have conditional validation based on some field in the main schema.

**Comment by serg06** [comment]
If you're willing to repeat yourself, this solution provides accurate typing; it's great if you're using tRPC.

```ts
const myObject = z
  .object({
    first: z.string(),
    second: z.string(),
  })
  .partial()
  .merge(
    z.object({first: z.string()})
      .or({second: z.string()})
  );  
```

**Comment by gradam** [comment]
@serg06 do you have an example on how you used it with tRPC? 
In my case TypeScript is not happy to accept ZodUnion in `.input()` in tRPC.

**Comment by serg06** [comment]
Nice catch @gradam , it doesn't work after all. :(

**Comment by Dmitry-Titov-K** [comment]
as a variant if your need set some paths

```typescript
const myObject = z
  .object({
    first: z.string(),
    second: z.string(),
    third: z.string(),
  }).superRefine((data, ctx) => {
   if(!data.thrid){
        ctx.addIssue({
          code: 'custom',
          path: ['first'],
          message: 'error message',
      });
        ctx.addIssue({
          code: 'custom',
          path: ['second'],
          message: 'error messaget',
      });
     }
  });
```

**Comment by frsyuki** [comment]
A type-safe approach:

```typescript
const notUndefined = z.custom<Exclude<any, undefined>>((val) => val !== undefined);

const schema = z.object({
  email: z.string().optional(),
  username: z.string().optional(),
  // other properties here
})
.and(z.union([
  z.object({email: z.undefined(), username: notUndefined}),
  z.object({email: notUndefined, username: z.undefined()}),
  z.object({email: notUndefined, username: notUndefined}),
], {errorMap: (issue, ctx) => ({message: "Either email or username must be filled in"})}));
```

A benefit of this approach is that parsed object is well-typed. Thus, following code doesn't cause type errors:

```typescript
const obj = schema.parse({
  email: "foo",
});

const emailOrUsername = obj.email ?? obj.username;
emailOrUsername.length;  // emailOrUsername is "string", not "string | undefined"
```

**Comment by 1mehdifaraji** [comment]
I've handled this situation with `if` and `else` like this :

```
export const validateGetOrderQuery = (({ query }, res, next) => {
  const { success, errors } = validateGetOrderId(query);

  const { success: userIdSuccess, errors: userIdErrors } =
    validateGetOrderUserId(query);

  if (success) {
    next();
  } else if (userIdSuccess) {
    next();
  } else if (!success) {
    const err: Error = new Error(JSON.stringify(errors));
    err.statusCode = 401;
    next(err);
  } else {
    const err: Error = new Error(JSON.stringify(userIdErrors));
    err.statusCode = 401;
    next(err);
  }
}) as RequestHandler;
```
This way the request should have `id` or `userId` query parameter otherwise it will throw error as response .

**Comment by exoego** [comment]
> A type-safe approach:
> 
> ```ts
> const schema = z.object({
>   email: z.string().optional(),
>   username: z.string().optional(),
>   // other properties here
> })
> .and(z.union([
>   z.object({email: z.undefined(), username: z.string()}),
>   z.object({email: z.string(), username: z.undefined()}),
>   z.object({email: z.string(), username: z.string()}),
> ], {errorMap: (issue, ctx) => ({message: "Either email or username must be filled in"})}));
> ```

This is type-safe, but the validation error message is not user-friendly. 
If both fields are missing,
```json
{
  "email":["Required"],
  "username":["Required"],
}
```

And if both fields are present,

```json
{
  "email": ["Expected undefined, received string"],
  "username": ["Expected undefined, received string"],
}
```

It appears that `errorMap` is not used as expected.

**Comment by exoego** [comment]
```typescript
function oneOf<A, K1 extends Extract<keyof A, string>, K2 extends Extract<keyof A, string>, R extends A & (
  Required<Pick<A, K1>> & { [P in K2]: undefined } |
  Required<Pick<A, K2>> & { [P in K1]: undefined }
)>(key1: K1, key2: K2): ((arg: A, ctx: RefinementCtx) => arg is R)  {
  return (arg, ctx): arg is R => {
    if ((arg[key1] === undefined) === (arg[key2] === undefined)) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: `Either ${key1} or ${key2} must be filled, but not both`,
      });
      return false;
    }
    return true;
  };
}

const schema = z.object({
  email: z.string().optional(),
  username: z.string().optional(),
  // other properties here
}).superRefine(oneOf("email", "username"));
```

This worked for me. It is type-safe and the error message is user-friendly.

**Comment by kwameglide** [comment]
Doesn't the use of `partial()` make all fields optional, essentially nullifying each field's validators...??

**Comment by bennycode** [comment]
Using `refine` or `or` on my Zod schema turns my schema from a `z.ZodObject` into a `z.ZodUnion`. Thus I am getting problems in my code (TS2416) that some parts are not assignable to the same property in base type (I am using implicit return types in most of my functions). Is there a workaround to fix this?

**Comment by sorenhoyer** [comment]
@mohamad-xtouch's solution worked the best for me.

**Comment by wojtekmaj** [comment]
So, now that superRefine is deprecated:

```ts
const schema = z.object({
  a: z.string().optional(),
  b: z.string().optional(),
}).check(ctx => {
    if (!ctx.value.a && !ctx.value.b) {
        ctx.issues.push({
          code: 'custom',
          message: 'a or b is required',
          input: ctx.value,
        });
    }
})

**Comment by KaKi87** [comment]
> Joi solve this problem with a `.when` method.

Actually, Joi solves this with [`or(...peers)`](https://joi.dev/api/?v=17.13.3#objectorpeers-options) :

> Defines a relationship between keys where one of the peers is required (and more than one is allowed)

And [`xor(...peers)`](https://joi.dev/api/?v=17.13.3#objectxorpeers-options) :

> Defines an exclusive relationship between a set of keys where one of them is required but not at the same time

I don't understand why that should be scripted manually rather than be built-in.
