### ISSUE TITLE
Generating an object from schema

### ISSUE THREAD

**Issue by KolbySisk** [vriad/zod#62]
This may not be a feature that makes sense to build, but it would be incredibly useful.

A normal workflow is to create a schema for your form state, generate a type, and then write the same object over again to use as the initial form state:

```
const formSchema = z.object({
  name: z.string(),
  email: z.string(),
});

type FormState= z.infer<typeof formSchema>

const initialFormState: FormState = {
  name: '',
  email: '',
 };

const [formState, setFormState] = useState<FormState>()
```

And now as your form grows so do these 2 objects.

I would love to be able to do something like this:
```
const formSchema = z.object({
  name: z.string().default(''),
  email: z.string().default(''),
});

type FormState= z.infer<typeof formSchema>

const initialForm = z.generate(formSchema);

const [formState, setFormState] = useState<FormState>(initialForm)
```

Currently I have a utility function I wrote that does this, it's not recursive and not very robust, but it does what I need and as a result my code is much cleaner. Everything can be updated simply by changing the Zod schema. Any thoughts on a feature like this?

**Comment by cybervaldez** [comment]
Looking for this too kinda similar to YUP’s cast function.

**Comment by vriad** [comment]
This will eventually be achievable with Zod transformations: #100

**Comment by vriad** [comment]
This is possible with the `.default` function in Zod 2: https://github.com/vriad/zod/tree/v2 (now in beta)

```ts
const formSchema = z.object({
    name: z.string().default(''),
    email: z.string().default(''),
  });

  type FormState = z.infer<typeof formSchema>;

  const initialForm = formSchema.parse({});
  console.log(initialForm);

  const [formState, setFormState] = useState<FormState>(initialForm);
```

**Comment by andredewaard** [comment]
@colinhacks Im quite late to this threat, But doesn't this defeat te purpose of validating the object afterwards?

so for example i want to create an form with name, email like above

```typescript
const formSchema = z.object({
    name: z.string().default(''),
    email: z.string().email().default(''),
  });

type FormState = z.infer<typeof formSchema>;

const initialForm = formSchema.parse({});

const submitForm = async () => {
  try {
    formSchema.parse(initialForm)
    // handle submit
  } catch (e) {
    // Handle form errors
  }
}
```

**Comment by mweel1** [comment]
Also need this, ability to create an empty object with the validation intacted.

**Comment by mrjackyliang** [comment]
Was just looking for something like this as well.

**Comment by dzbo** [comment]
How about:

```
formSchema.optional().parse({})
```

**Comment by senpro-ingwersenk** [comment]
Has this become a feature yet? I ran into an error with the schadcn-ui form which requires defaults and I would love to pull said defaults off my scheme.

thanks!

**Comment by anthonyalayo** [comment]
same thoughts as @senpro-ingwersenk , is there a solution to this today?

**Comment by ahrjarrett** [comment]
[@traversable/zod](https://github.com/traversable/schema/tree/main/packages/zod#zxdefaultvalue) supports creating a default value from a schema.

It was built specifically with the form use case in mind.

Example from the docs:

```typescript
import { z } from 'zod'
import { zx } from '@traversable/zod'

const MySchema = z.object({
  a: z.number(),
  b: z.object({
    c: z.string(),
    d: z.array(z.boolean())
  })
})

// by default, primitives are initialized as `undefined`:
const defaultOne = zx.defaultValue(MySchema)
console.log(defaultOne) // => { a: undefined, b: { c: undefined, d: [] } }

// to configure this behavior, use the `fallbacks` property:
const defaultTwo = zx.defaultValue(MySchema, { fallbacks: { number: 0, string: '' } })
console.log(defaultTwo) // => { a: 0, b: { c: '', d: [] } }
```

Tagging @senpro-ingwersenk @anthonyalayo @mrjackyliang
