### ISSUE TITLE
Request: nonempty for string

### ISSUE THREAD

**Issue by KolbySisk** [vriad/zod#63]
I'm using MUI for my forms and it requires my default input values to be an empty string. Of course that means an empty input will pass Zod validation because it is indeed a string and does exist.

Currently im using `refine` and checking the length is greater than 0. It works fine.

But a nice and simple solution would be a `nonempty` method that rejects empty strings.

**Comment by vriad** [comment]
I took this opportunity to implement a lot of built-in refinement types. It's been on my todo list for a while. Upgrade to zod@1.7 to use those (including `.nonempty` on string schemas).

**Comment by bryantobing12** [comment]
what will be the replacement for this, since `.nonempty` is now deprecated? 

the doc only says to use `z.string().min(1)` but in my case, I need to validate if its an empty string

**Comment by kendall-wahnschaffe** [comment]
```
z.string().nonempty().min(2, {message: 'Must be at least 2 characters'})
```

does not behave the same as:

```
z.string({ required_error: 'String must contain at least 1 character(s)'}).min(2, {message: 'Must be at least 2 characters'})
```

Is this possible to do without using an object?

**Comment by xsjcTony** [comment]
@colinhacks Sorry to bother, but can you please briefly explain why empty string is considered valid when it's required (by default)?

I came from `yup` so it's actually a little bit weird to me. Writing `z.string().min(1, { message: 'xxx is required' })` on every required string field makes no sense to me instead of just simply writing `z.string()`

Thanks for that.

**Comment by p-runge** [comment]
The reason for that probably is that `z.string()` shall just check for the type itself, and `""` is indeed of type string.
But I feel you. I most cases I face it would be more handy to handle `""` as "failed" (e.g. in validating forms, where pretty much everything is defaulting to `""`). And to check for that using `.min(1)` with a regarding error message instead of `Required` does not feel satisfying.
What was the reason to actually deprecate `.nonempty()` at all? Did it have a different purpose prior to v1.7? Maybe it would be an option to redefine its purpose and un-deprecate it then?

**Comment by curtisburns** [comment]
Just encountered this problem when validating form data submitted using React Hook Form, which will send empty strings even if the field hasn't been touched by the user. The reasoning is that they are following HTML standards, fine. 

But, I don't understand why validation should be bypassed with an empty string when this isn't the behaviour anyone would expect when handling form data with required fields. Seems like this is an issue that most devs are likely to encounter when using this library. I can't find it explicitly mentioned anywhere what the replacement for `.nonempty()` is. It's a common validation requirement so it would be good to have some info on this. I'll be using `.min(1, { message: 'Required' })` in the meantime but are there any plans for a more intuitive solution in the near future?

**Comment by curtisburns** [comment]
> Allowed
> 
> ```ts
> {
>   field: ' '
> }
> ```

Good catch! Thanks 👍

**Comment by stefanhayden** [comment]
a way to check for an empty string is
```
z.string()
  .transform((t) => t?.trim())
  .pipe(
    z.string().min(1)
  )
```

which you could package up like:
```
const nonempty = z.string()
  .transform((t) => t?.trim())
  .pipe(
    z.string().min(1)
  )

z.string().pipe(nonempty)
```

a little annoying but it works.

**Comment by rwieruch** [comment]
Using `zod.string()` instead of `z.string()` for my cases now :)

```
import { z } from 'zod';

const zod = {
	string: () => z.string().trim().min(1, { message: 'Is required.' }),
};

export { zod };
```

**Comment by nemanjahifolks** [comment]
This is very annoying and ugly to use `min(1, 'message...')` instead of simple `required()` with reasonable default message.

**Comment by npearson72** [comment]
I'm not getting a deprecation warning for `string().nonempty()`, and it does appear to work as expected. However it is not in the README.

Can someone point out where the deprecation notice was published? Or has that be rolled back?

**Comment by p-runge** [comment]
> I'm not getting a deprecation warning for `string().nonempty()`, and it does appear to work as expected. However it is not in the README.
> 
> Can someone point out where the deprecation notice was published? Or has that be rolled back?

That's interesting. I browsed through the release notes, and found out I get the deprecated note up to `"zod": "3.21.0"`. If I install `"zod": "3.21.1"` it vanishes – which is strange, since I can't find anything related in that version's release notes:
https://github.com/colinhacks/zod/compare/v3.21.0...v3.21.1

It even refactors a test from using `string().nonempty` to `string().min(1, "nonempty");`.
It look to me as if the deprecated note got swallowed accidentally as a side-effect from another thing happening in that version, but I didn't dig that deep.
So my guess is – although it's not marked anymore – it still is meant to be deprecated as is.

**Comment by kashif-ghafoor** [comment]
in documentation nonempty() is only mentioned for arrays and sets. but I am using zod version 3.21.4 and  z.string().nonempty() is working perfectly fine.
I get IntelliSense on z.string() for nonempty() and if string is empty it throws error.

**Comment by lloydjatkinson** [comment]
I just encountered this issue when using `react-hook-form` which requires `defaultValues` for strings to be `''` - similar issue as the OP. This seems like a very common need.

The solutions mentioned here with the trim and minimum length work but I think perhaps a better solution is this. This way makes seems more explicit and avoids the need to override the default message too.

```ts
z.string().refine((value) => value !== ''),
```

**Comment by vhscom** [comment]
> a little annoying but it works.

LGTM. Hope it works! ><

**Comment by vtrphan** [comment]
any news on this? i still don't get why nonEmpty is deprecated ?

**Comment by Sadeghbayan** [comment]
```
  street: z
        .string({
            required_error: 'Street is required',
        })
        .refine((data) => data.trim() !== '', {
            message: 'Street can not be an empty string',
        }),
```

that's too much for every required field.

**Comment by lloydjatkinson** [comment]
> ```
>   street: z
>         .string({
>             required_error: messages.street,
>         })
>         .refine((data) => data.trim() !== '', {
>             message: messages.street,
>         }),
> ```
> 
> that's too much for every required field.

Does my solution help you?

**Comment by sumitbishti** [comment]
I have tried all the solutions presented in this thread, NONE of them works as of today for strings with just space(s).

**Comment by lloydjatkinson** [comment]
I'm not sure how that can be possible, my solution uses `trim()`

**Comment by sumitbishti** [comment]
Even i'm using trim() and/or min() and every possible permutation of them. Not working!

**Comment by lloydjatkinson** [comment]
>  NONE of them works

> Even i'm using trim() and/or min() and every possible permutation of them. Not working!

> Edit: Yup, trim() works

![image](https://github.com/colinhacks/zod/assets/5633938/e0242882-2e6c-47f1-b0fe-55ef5a619267)

**Comment by danwebnl** [comment]
I am afraid this thread still doesn't answer this case:

- the value is required and it has to have a minimal amount of characters (eg 3 characters)

How can Zod provide this?
- check if the value is empty and in that case provide error message (eg 'this field cannot be empty')
- check if the value has the minimal amount of characters and in that case provide another error message (eg 'you need to provide at least 3 characters')

If somebody could provide an example fr this case it would be really great.

**Comment by Sadeghbayan** [comment]
@danwebnl how about this? 

```
const schema = z
  .string({
    required_error:"This field cannot be empty"
  })
  .refine((data) => data.trim() !== '', {
    message:"This field cannot be empty",
  })
  .refine((data) => data.length >= 3, {
    message: 'You need to provide at least 3 characters',
  });
```

**Comment by danwebnl** [comment]
> @danwebnl how about this?
> 
> ```
> const schema = z
>   .string({
>     required_error:"This field cannot be empty"
>   })
>   .refine((data) => data.trim() !== '', {
>     message:"This field cannot be empty",
>   })
>   .refine((data) => data.length >= 3, {
>     message: 'You need to provide at least 3 characters',
>   });
> ```

This works great, thank you for the quick answer!

**Comment by augusto-dmh** [comment]
just using logical not operator would be enough.

**Comment by pa4080** [comment]
If you do not want to repeat all conditions multiple time you can assign them to a function and then use that function within the schema. Something like:

```javascript
const zStringReq = (key?: string) =>
  z.string().trim().min(1, { message: `${key ? `${key} is ` : ""}Required!` });

const envSchema = z.object({
  ACCOUNT_ID: zStringReq(),
  API_TOKEN: zStringReq(),
  API_ENDPOINT: zStringReq(),
});
```

**Comment by octopus198** [comment]
I don't know if this helps but when I follow the tutorial of Nextjs, they only write name: z.string() and it works. 
If the user doesn't input anything, the returned value of the name field is null, which is caught by Zod. I write the same code for my project but somehow my name field always returns an empty string name: '', not null as I expected. 
Anyway, I ended up using z.string().trim().min(1, { "Required!" }); and it works. But I'm still very curious why the name field in the tutorial returns null.
Here's the tutorial code for your reference:
[](https://github.com/vercel/next-learn/blob/main/dashboard/final-example/app/lib/actions.ts)

**Comment by danwebnl** [comment]
> I don't know if this helps but when I follow the tutorial of Nextjs, they only write name: z.string() and it works. If the user doesn't input anything, the returned value of the name field is null, which is caught by Zod. I write the same code for my project but somehow my name field always returns an empty string name: '', not null as I expected. Anyway, I ended up using z.string().trim().min(1, { "Required!" }); and it works. But I'm still very curious why the name field in the tutorial returns null. Here's the tutorial code for your reference: https://github.com/vercel/next-learn/blob/main/dashboard/final-example/app/lib/actions.ts

Thank you kindly for sharing this informative update!

**Comment by mashwishi** [comment]
> Came across this thread and another while trying to resolve blank strings being passed in required string fields that had a minimum length requirement; ie:
> 
> ```ts
> {
>   field: z.string().min(1)
> }
> ```
> 
> Allowed
> 
> ```ts
> {
>   field: ' '
> }
> ```
> 
> [A feature request](https://github.com/colinhacks/zod/issues/653) from last year had a solution for me here, and I think the easiest way to implement the check that used to be happening with noempty() can be covered by using
> 
> ```ts
> z.string().trim().min(1)
> ```

i still can access with spaces

**Comment by matheuscdd** [comment]
Something I did in my project was to use a regex. When I used refine, I could only put it last, with regex I didn't need to

```js
const required = /^[^$]/;
const user = z.object({
    name: z.string().regex(required).min(5),
});
```
