### ISSUE TITLE
How to best mix required and optional properties?

### ISSUE THREAD

**Issue by rauschma** [vriad/zod#65]
I expected this to work:

```ts
const AnObjSchema = z.object({
  file: z.string(),
  author: z.string().optional(),
  tags: z.array(z.string()).optional(),
});

type AnObj = z.infer<typeof AnObjSchema>;
// type AnObj = {
//   file?: string; // should not be optional
//   author?: string;
//   tags?: string[];
// }
```

Alas, property `.file` is not required in the inferred type. Do I have to do an intersection type of two object types?

**Comment by vriad** [comment]
This happens when you aren't using strict mode in your `tsconfig.json`:

https://github.com/vriad/zod#typescript-versions

**Comment by rauschma** [comment]
Thanks and sorry for the noise!

Apparently VS Code ignores `tsconfig.json` in TS files that only exist in RAM. Once I saved my experiments to disk, the problems did indeed go away.

**Comment by vriad** [comment]
No problem at all 👍 

And yep, forgetting to save my `tsconfig.json` has caused me much grief. Usually I save it, then restart the TS server from the Command Palette in VSCode. Otherwise there's some variability in when it takes effect...sometimes a few seconds, sometimes a lot longer.

**Comment by rauschma** [comment]
For me, it was even weirder: As a scratch pad, I created a new (unsaved) document and switched it to TypeScript mode. The inferred types that TypeScript showed me there were as described at the beginning of this issue. It looks like TS used default settings and ignored my `tsconfig.json`. Once I saved the document, everything was OK.

**Comment by vriad** [comment]
Fascinating. And extremely odd. 🤷‍♂️

**Comment by jasonk** [comment]
I realize it's a couple of years late, but the reason this happens is that until you have saved the file it doesn't have a location on disk, so there is no way for TypeScript to find the appropriate `tsconfig.json` file until you save it and give it a starting point..
