### ISSUE TITLE
Union errors path

### ISSUE THREAD

**Issue by euphocat** [vriad/zod#67]
I was wondering why errors path is inlined within the message when using union types:
```typescript
try {
    const parser = z.array(
      z.union([
        z.object({ messages: z.array(z.string().nonempty()) }),
        z.string(),
      ]),
    );

    parser.parse([{ messages: [''] }]);
  } catch (e) {
    // eslint-disable-next-line no-console
    console.log('errors: ', JSON.stringify(e.errors));
  }
```
gives:
```
[{"path":[0],"message":"\n\tunion option #0: messages.0: Value cannot be empty string\n\tunion option #1: Non-string type: object"}]
```

But why not (?)
```
[{"path":[0, "messages", 0],"message":"Value cannot be empty string"}]
```

**Comment by vriad** [comment]
This is a tricky subject. 

There's no generalizable way for Zod to know which of the two union types is the one that "should have passed". All it knows is that the data you passed in is neither of these:

```
z.object({ messages: z.array(z.string().nonempty()) })
z.string()
```

You're basically asking Zod to guess which schema in the union you were "trying for", but it would only work in a limited number of cases. Consider this:

```ts
z.union([
  z.object({ a: z.string() }),
  z.object({ b: z.string() }),
]).parse({ c: 5 })
```

What should the error path be?

**Comment by vriad** [comment]
Perhaps a better solution for types like this is to provide a list of "suberrors" with full error information for each of the components. I'll look into this when I have time.

**Comment by alfonmga** [comment]
> @euphocat
> 
> This is a tricky subject.
> 
> There's no generalizable way for Zod to know which of the two union types is the one that "should have passed". All it knows is that the data you passed in is neither of these:
> 
> ```
> z.object({ messages: z.array(z.string().nonempty()) })
> z.string()
> ```
> 
> You're basically asking Zod to guess which schema in the union you were "trying for", but it would only work in a limited number of cases. Consider this:
> 
> ```ts
> z.union([
>   z.object({ a: z.string() }),
>   z.object({ b: z.string() }),
> ]).parse({ c: 5 })
> ```
> 
> What should the error path be?

Excuse me, is there any workaround for this issue on Zod's v2 version? I liked the proposed idea by @chrbala about [union resolver functions](https://github.com/vriad/zod/issues/117#issuecomment-674449188).

**Comment by vriad** [comment]
Zod does try to semi-intelligently guess which element of the union was closest to matching the input. For instance the initial example in this issue:

```ts
 const parser = z.array(
      z.union([
        z.object({ messages: z.array(z.string().nonempty()) }),
        z.string(),
      ]),
    );

    parser.parse([{ messages: [''] }]);
```

now throws this error:

```
{
  "success": false,
  "error": {
    "issues": [
      {
        "code": "too_small",
        "minimum": 1,
        "type": "string",
        "inclusive": true,
        "path": [
          0,
          "messages",
          0
        ],
        "message": "Should be at least 1 characters"
      }
    ]
  }
}
```

But generally speaking Zod throws a ZodError containing a `ZodInvalidUnionIssue` that contains the errors thrown by each element of the union:

```ts
export interface ZodInvalidUnionIssue extends ZodIssueBase {
  code: typeof ZodIssueCode.invalid_union;
  unionErrors: ZodError[];
}
```
