### ISSUE TITLE
Can't build in my project with strictPropertyInitialization: true

### ISSUE THREAD

**Issue by MikeyBurkman** [vriad/zod#7]
Because zod isn't compiled when it's distributed in npm, my TS compiler tries to compile it. However, my project has `strict: true` in its config options, with no strict flags turned off, and so it ends up failing to build because zod has `strictPropertyInitialization` set to false. I get a handful of errors like `Property 'schema' has no initializer and is not definitely assigned in the constructor`

I currently can only use this library in my app if my strict compile options are set to what zod has, which is definitely not preferable. (And that's a shame because I _really_ like the idea of this and I too was _this_ close to trying to write my own library after being unhappy with the status quo.)

I think it would help a lot if the project was actually pre-compiled, and the JS + .d.ts files were distributed in npm, instead of the raw TS files.

(Also, side note that is kind of related to my above suggestion: I run our app using ts-node, and I get `Cannot use import statement outside a module` when ts-node tries to import zod. I'm pretty sure that this would also be fixed by releasing the compiled code instead of the raw TS.)

**Comment by vriad** [comment]
@MikeyBurkman Just published a new version (zod@1.0.7) that's pre-compiled, should solve all the issues you mentioned. Also all the tsconfig settings are now as strict as possible. Sorry for the inconvenience - I didn't expect this package to get so popular so I didn't exactly follow best npm practices. 

Closing now, let me know if any of these issues persist!
