### ISSUE TITLE
Correct way to use a third party Class/type in a Zod schema object?

### ISSUE THREAD

**Issue by callumlocke** [vriad/zod#71]
I'm trying to do this, but TypeScript complains:

```js
  z.object({
    slug: z.string().min(1).max(255),
    title: z.string().max(255),
    timeStart: Timestamp,
  })
```

Error:
```
Type 'typeof Timestamp' is missing the following properties from type 'ZodType<any, ZodTypeDef>': _type, _def, parse, is, and 5 more.
```

I basically want to make a schema that asserts that `timeStart` is an instance of the class `Timestamp` (which itself is a class I imported from a third party library).

How can I do this? Sorry if it's obvious.

Thank you for writing this library by the way, it's by far the best solution for TypeScript runtime checking I've found (and I've tried many).

**Comment by vriad** [comment]
Hey Callum,

It's definitely not obvious. It may make sense to add a method specifically for this use case, I'll add it to the this. 

In the meantime, it's already achieveable but it's not super pretty:

```ts
const TimestampSchema: z.ZodType<Timestamp> = z.any().refine(x => x instanceof Timestamp);
```

`z.any()` lets anything through, but with the `.refine` makes sure that it's an instance. 

You can "hard code" the type you want to validate by casting to `z.ZodType<YourTypeHere>`. Inference works as you'd expect:

```ts
type Timestamp = z.infer<typeof TimestampSchema>;
const time: Timestamp = new Timestamp(); // works fine
```

**Comment by callumlocke** [comment]
Your suggestion using `z.ZodType` and `.refine()` works for me, thanks.

Yes, it's not super pretty at first glance. It does make sense now I see it, but it feels like a clever trick. I agree that something like `z.instanceOf(Foo)` would be a good addition for my specific use case. But I can see myself needing to use that `z.any().refine(fn)` trick again for other special cases. Maybe it would be good to provide a wrapper with a more intuitive name, like `z.custom()`? I guess it would also need to take a generic to set the type, something like:

```ts
const x: = z.custom<MyType>((value: any) => {
  // examine value and return true/false
}))

z.infer<x> // MyType
```

One more thing while I'm here: I think the name `z.ZodType<T>` might be better as `z.Schema<T>`, as you're using the word 'schema' throughout the readme. (Unless I've misunderstood what this utility is?)

Just to reiterate, I am in love with this library! Thank you for writing it. It's made writing TypeScript a joy.

**Comment by vriad** [comment]
Lots of great ideas here! Just added all three of these things to my todo list 🤙

I follow up here when they're implemented.
