### ISSUE TITLE
Error reporting is useless when using z.function().implement()

### ISSUE THREAD

**Issue by ivosabev** [vriad/zod#74]
I have multiple functions written with `z.function().implement()` that call each other and one of them was returning `undefined` instead of the an object fitting its return type. It took me about an hour to find the exact function that was throwing due to error messages like these that do not tell you anything about which object schema or function is throwing:

```
TypeError: Cannot convert undefined or null to object at Function.keys (<anonymous>)

      at ZodObject.parse (node_modules/zod/src/parser.ts:90:32)
      at Object.<anonymous> (node_modules/zod/src/parser.ts:268:35)
      at step (node_modules/zod/lib/src/parser.js:32:23)
      at Object.next (node_modules/zod/lib/src/parser.js:13:53)
      at fulfilled (node_modules/zod/lib/src/parser.js:4:58)
```

```
Non-object type: undefined

      at new ZodError (node_modules/zod/src/ZodError.ts:10:5)
      at Function.ZodError.create (node_modules/zod/src/ZodError.ts:17:19)
      at Function.ZodError.fromString (node_modules/zod/src/ZodError.ts:35:21)
      at ZodObject.parse (node_modules/zod/src/parser.ts:84:51)
      at Object.<anonymous> (node_modules/zod/src/parser.ts:268:35)
      at step (node_modules/zod/lib/src/parser.js:32:23)
      at Object.next (node_modules/zod/lib/src/parser.js:13:53)
      at fulfilled (node_modules/zod/lib/src/parser.js:4:58)
```

I am writing in TS, so this might be related to the TS compiler, but the errors are still useless if they don't tell you which schema or function is throwing.

**Comment by vriad** [comment]
Can you share some code and maybe an idea of how this can be improved? Perhaps a reference to the throwing schema could be included in the ZodError object? Schemas don't have any sort of identifier so there isn't an obvious way of indicating which schema or function is throwing.

**Comment by ivosabev** [comment]
I've tried some code, but the only solution would be to add optional metadata properties.

This way you can keep defining anonymous schemas/types as you do right now.

And the second approach would be to supply the meta properties. I see someone opened a related issue (#76).

```typescript
const userSchema = z.object({
  id: z.number(),
  name: z.string(),
}).meta({
  name: 'User'
});
```

**Comment by vriad** [comment]
I'm working on a big overhaul of the error handling system. I'm adding a `zodPath` property to the errors that will give you the path through the Zod schema hierarchy, e.g. `['function', 'tuple', 0, 'id']`. You should be able to follow the execution of the parsing to find exactly where the error is being thrown. 

I'm still a little dubious about adding metadata to the schemas, especially if you want to write custom validations/error messages that assume the existence of a particular metadatum. That seems like a fragile antipattern to me.

Could you send a code sample of these two ZodFunctions that call each other? I'd like to add that case into the testing suite, and I want to make sure this use case is covered.

**Comment by vriad** [comment]
I published a major overhaul to the error handling system in zod@1.8. Every Zod suberror has an error code associated with it. Most notably, the errors thrown by function schemas will only every have two possible codes: `ZodErrorCode.invalid_args` and `ZodErrorCode.invalid_return_type`. These errors contain additional properties (`argumentsError` and `returnTypeError` respectively) that provide additional information about the actual validation issues:

```ts
const myFunc = z.function(
  z.tuple([ z.string() ]), 
  z.boolean()
).implement((str)=>str.length > 5);

myFunc("asdf") // error
```

The resulting error:

```
ZodError {
  "errors": [
    {
      "code": "invalid_arguments",
      "argumentsError": ZodError {
        "errors": [
          {
            "code": "invalid_type",
            "expected": "string",
            "received": "number",
            "path": [
              "0"
            ],
            "message": "Invalid input: expected string, received number"
          }
        ]
      },
      "path": [],
      "message": "Invalid function arguments"
    }
  ]
}
```
