### ISSUE TITLE
[Request] Create schema from JSON

### ISSUE THREAD

**Issue by cybervaldez** [vriad/zod#75]
I’ve been using YUP which can’t do that and recently saw zod. Just wondering if this is on the table? A use case is a dynamically made schema by my users. Something like zod.importJSON(jsonOBJ)

**Comment by vriad** [comment]
It's certainly possible but it would break type inference. You can't pass a blob of untyped data into a hypothetical `zod.importJSON(blob)` function and get a statically typed validator out of it. Is that a problem?

**Comment by cybervaldez** [comment]
Not a problem because i'm just expecting primitives from the import. Someone made [json-schema-to-yup](https://www.npmjs.com/package/json-schema-to-yup) for this but it has a lot of issues when yup gets updated.

**Comment by tonyxiao** [comment]
what about the inverse of that? Turn a Zod schema into JSONSchema? Of course, a limited set of it given that zod can be more expressive than jsonschema.

**Comment by lazharichir** [comment]
@tonyxiao that's exactly what I am looking for because basically:
- all my backend services use `fastify` (rest framework like Express)
- each route has a JSON Validator built-in
- each backend service exposes its OpenAPI Spec thanks to these json schemas

So basically, I am looking at a Zod to JSON Schema helper to avoid having to double specify each type. Let me know if you find anything!

**Comment by cybervaldez** [comment]
> It's certainly possible but it would break type inference. You can't pass a blob of untyped data into a hypothetical `zod.importJSON(blob)` function and get a statically typed validator out of it. Is that a problem?

Is this going to be on the roadmap?

**Comment by vriad** [comment]
@tonyxiao @cybervaldez @lazharichir This is possible but out of scope for Zod core, in my opinion. I don't want to be responsible for maintaining a bunch of "generate X from Zod" or "generate X from Zod" utilities. Those are best implemented as separate tooling.

Frankly I think generating Zod schemas from JSON schema is a bit of an antipattern and you should just use a JSON-schema validation library in that case. The point of Zod is the type inference, and that's not possible with a JSON import. 

If anyone want to take a stab at implementing a "Zod to JSON schema" generator I recommend looking at the parser (src/parser.ts) as a starting point. It's just a recursive function containing a giant switch statement for all the possible subclasses of ZodType. You'll also need to do some basic cycle detection to avoid infinite loops for recursive schemas.

**Comment by mrhammadasif** [comment]
I have reworked the library zod-to-json-schema to work with latest zod@3.1.0

For those who want to test it, i have create a PR for that https://github.com/StefanTerdell/zod-to-json-schema/pull/2

**Comment by tonyxiao** [comment]
> It's certainly possible but it would break type inference. You can't pass a blob of untyped data into a hypothetical `zod.importJSON(blob)` function and get a statically typed validator out of it. Is that a problem?

Found this amazing repo that may actually be able to solve this problem in cases where JSONSchema is defined in TS file rather than raw json file.
