### ISSUE TITLE
Similar to Yup’s meta properties?

### ISSUE THREAD

**Issue by cybervaldez** [vriad/zod#76]
This is an extremely useful feature yup had that is keeping me from transitioning to zod, basically each schema object have additional properties that can be used for validation and other use case.

**Comment by vriad** [comment]
I'm considering this but I'm not sure I understand the use case. Can you elaborate on how exactly you hope to use this? Error customization? Custom validations?

**Comment by cybervaldez** [comment]
primarily using it as part of refine's validation is one:

`const myString = z.string().meta({ length : 255 }).refine( (val, meta) => val.length <= meta.length, ({length})=>"String can't be more than ${length} characters");`

but equally important if zod would implement something like yup's [describe](https://github.com/jquense/yup#mixeddescribe-schemadescription):
`const input = myString.describe() // { type : 'string', meta : { length : 255 } }`

so in our UI we can easily build our input based on that.
`<input ... maxlength={input.meta.length} />`

**Comment by chrbala** [comment]
Seems like there are quite of lot of arbitrary places where UI could be driven from metadata in some way:
* max length on a field gets set on the input
* max length on an array disables or hides an "add row" button

More complex metadata could be something like data driven UI allowing for selection of various complex forms based on a union type. 

At some level it seems like there could be a question of whether zod:
* allows arbitrary fields like this suggestion
* generates user-accessible metadata based on the built-ins like ``z.string().max(5)``
* some combination of the above

**Comment by ivan-kleshnin** [comment]
I'm using Yup's `meta` to add human-readable validation rules that are not used directly but can be displayed in forms. 
Very useful feature. In this way you don't have to support a second tree of stuff which is more ergonomic (rules right behind their descriptions).

**Comment by vriad** [comment]
I'm afraid I'm getting more and more opposed to this over time. All of these use cases are out of scope for Zod and should be implemented with programmatic constructs external to Zod. 

**Form UI**

@ivan-kleshnin 

```
type MyFormInput = {
  name: string;
  label: string;
  placeholder: string;
  validator: z.ZodSchema<unknown>;
};
type MyForm = MyFormInput[];

const fields:MyForm = [ /* define form here */ ];
```

Then you can loop over the form fields to build your form. To get the type of each ZodSchema you can use `._def.t`:

```ts
const input: MyFormInput = "whatever" as any;
input.validator._def.t; // => z.ZodTypes
```

If you want to get really fancy and still get type inference, use a class. Here's a toy example of a `ZodForm` class. This could easily be a library unto itself.

```ts
class ZodForm<T extends MyFormInput[] = []> {
  inputs: T;
  constructor(inputs: T) {
    this.inputs = inputs;
  }

  input = <Input extends MyFormInput>(input: Input): ZodForm<[...T, Input]> => {
    return new ZodForm([...this.inputs, input]);
  };
}
```

**For metadata driven validations**

@cybervaldez 

You should use language-level constructs for this too. 

```ts
const maxRefinement = (max: number) => ({
  check: (val: string) => val.length <= max,
  message: `String can't be more than ${max} characters`,
})

const myString = z.string().refinement(maxRefinement(12));
```

More generally, I think of Zod as a foundation for typesafety in an application, designed to be built on top of. The use cases you gave are certainly valid, though they're the sort of domain-specific/application-specific tooling you should build yourself on top of Zod. Zod shouldn't be a wrapper for it, it should be a component within it. 👍

**Comment by ivan-kleshnin** [comment]
I kinda agree. This is solvable in user-land so maybe it's really not worth adding at the moment. 
More code = More tests = Slower development.

**Comment by vriad** [comment]
given the lack of dissent, i'm gonna close this

**Comment by jedwards1211** [comment]
There are problems I've only been able to solve by attaching metadata at multiple levels of the Zod schema and deeply inspecting the Zod schema at type time/runtime.  Here's what I've used to accomplish that:

```
import z from 'zod'

export class ZodMetadata<
  T extends z.ZodTypeAny,
  M extends object
> extends z.ZodEffects<T> {
  constructor(def: ZodEffectsDef<T>, public metadata: M) {
    super(def)
  }

  unwrap() {
    return this._def.schema
  }
}

export function zodMetadata<T extends z.ZodTypeAny, M extends object>(
  schema: T,
  metadata: M
): ZodMetadata<T, M> {
  return new ZodMetadata(schema.refine(() => true)._def, metadata)
}
```

It's basically just a `no-op` `.refine()` that adds a `metadata` field.

Then you can do any deep mapping/filtering you want at runtime, or even at type time:

```ts
type OutputForVersion<
  Z extends z.ZodTypeAny,
  V extends number
> =
  S extends ZodMetadata<infer T, infer M>
  ? M extends { version: infer SchemaVersion extends number }
    ? IsGreaterThanOrEqual<SchemaVersion, V> extends true
      ? OutputForVersion<T, V>
      : never
    : OutputForVersion<T, V>
  : IsAny<z.output<S>> extends true
  ? any
  : S extends z.ZodArray<infer T>
  ? OutputForVersion<T, V> extends never
    ? never
    : Array<OutputForVersion<T, V>>
  : S extends z.ZodOptional<infer T>
  ? OutputForSingleVersion<T, V> extends never
    ? never
    : OutputForSingleVersion<T, V> | undefined
  // etc
  : z.output<S>
```

**Comment by vadimyen** [comment]
@jedwards1211, how do you use the `OutputForVersion` type?

**Comment by jedwards1211** [comment]
@vadimyen  here's my blog post about the whole system: https://www.jcore.io/articles/schema-versioning-with-zod
