### ISSUE TITLE
[bug] Cannot parse objects intersection

### ISSUE THREAD

**Issue by zaverden** [vriad/zod#82]
# Description

I have following description for `ShapeEntity`
```typescript
import * as z from "zod";

const SquareData = z.object({
  type: z.literal("square"),
  data: z.object({
    width: z.number(),
    height: z.number(),
  }),
});
const CircleData = z.object({
  type: z.literal("circle"),
  data: z.object({
    radius: z.number(),
  }),
});

const ShapeData = z.union([SquareData, CircleData]);
const ShapeEntity = z.intersection(z.object({ id: z.string() }), ShapeData);
type ShapeEntity = z.infer<typeof ShapeEntity>;
```

When I try to parse valid circle, zod fails
```typescript
try {
  let circle = {
    id: "id",
    type: "circle",
    data: { radius: 123 },
  };
  ShapeEntity.parse(circle);
  console.log("circle success");
} catch (error) {
  console.log(error.message);
  // Left side of intersection: Unexpected key(s) in object: 'type', 'data'
  // Right side of intersection: 
  //     union option #0: Unexpected key(s) in object: 'id'
  //     union option #1: Unexpected key(s) in object: 'id'
}
```

# Workaround
It can work if I redefine type as union of merged parts
```typescript
const ShapeEntityBase = z.object({ id: z.string() });
const ShapeEntity = z.union([
  ShapeEntityBase.merge(SquareData),
  ShapeEntityBase.merge(CircleData),
]);
```
But it does not feel native, because in typescript I define type as `Base & (Opt1 | Opt2)`, not as `(Base & Opt1) | (Base & Opt2)`

**Comment by vriad** [comment]
Yeah, this is definitely counterintuitive, but it is the intended behavior.

Intersections in Zod are extremely "dumb" — they just pass the data into the two schemas being intersected. If either one fails, the intersection throws as well.

This interacts in some unexpected ways with how Zod handles object schemas. By default, Zod object schemas do not allow unknown keys. So when you pass in this:

```ts
{
  id: "id",
  type: "circle",
  data: { radius: 123 },
}
```

it will fail validation for both `z.object({ id: z.string() })` and ShapeData.

One way to avoid this is to make both of the intersection components `.nonstrict` so they don't throw errors when they encounter unexpected keys:

```ts
const ShapeEntity = z.intersection(
  z.object({ id: z.string() }).nonstrict(), 
  ShapeData.nonstrict()
);
```

But I think this approach is more appealing and intuitive:

```ts
const BaseShape = z.object({ id: z.string() })

const SquareData = BaseShape.extend({
  type: z.literal("square"),
  data: z.object({
    width: z.number(),
    height: z.number(),
  }),
});

const CircleData = BaseShape.extend({
  type: z.literal("circle"),
  data: z.object({
    radius: z.number(),
  }),
});

const ShapeData = z.union([ SquareData, CircleData ])
```

I understand your opinion that this doesn't feel "native". Ironically I chose to disallow unknown keys by default _because_ it's more consistent with how TypeScript treats object types. Check out the [Unknown keys](https://github.com/vriad/zod#unknown-keys) section to read more about that. Unfortunately there will always be perceived inconsistencies when you're dealing with type systems like this, so I'm not planning to change this.

**Comment by zaverden** [comment]
could you please update the "intersections" section in the documentation
https://github.com/vriad/zod#intersections

At the moment it says that I can use intersection on object schemas. It is kind of misleading since `Teacher.parse` always fails

**Comment by zaverden** [comment]
And more general thought.

If you check [intersections in TS docs](https://www.typescriptlang.org/docs/handbook/advanced-types.html#intersection-types) it focuses on objects. So main purpose it to intersect 2 object structures.

As you said above intersection on 2 strict objects schemas intentionally fails to parse any structures as proper way is to use `.merge`.

May be Zod should not provide `intersection` method at all.
