### ISSUE TITLE
Asynchronous validations

### ISSUE THREAD

**Issue by chrbala** [vriad/zod#87]
There's support for validating [promise types](https://github.com/vriad/zod#promises), but I don't see a way to create async validators.

What I'm thinking of is something like this:

```js
const foreignKey = z.string().refine(idExistsAsync, {
  message: "ID not found",
});
foreignKey.parseAsync("1234")
```

Where ``idExistsAsync`` is some function that asynchronously checks some backend to make sure that the value is valid. It returns a promise. Of course this would mean that the entire schema becomes async, so there are some other concerns here when async values are used as fields on objects.

**Comment by vriad** [comment]
Very good idea — on the todo list. In zod@2 I'm considering modifying `.parse()` to always return a Promise. That eliminates the messy dichotomy between parse and parseAsync. If anyone has strong opinions on this chime in! 

> If anyone wants to submit a PR for this this get in touch with me [on Twitter](https://twitter.com/vriad) and I can walk you through how I'd recommend doing it. Otherwise I'll update this issue when I get around to it.

**Comment by chrbala** [comment]
I agree that the default should be to validate async if that would be okay as a breaking change. It may still make sense to have a synchronous version that requires all parts of the schema to operate synchronously. So maybe ``parse`` and ``parseSync`` would make sense.

**Comment by ivan-kleshnin** [comment]
Am I right in understanding that `Z.promise(syncScheme)` rules cannot be nested inside sync rules.

So, ror example:

```
 let scheme = Z.promise(Z
  .object({
    username: Z.string().min(5).max(50),
    password: Z.string().min(10).max(50),
    asyncData: Z.promise(Z.string())
  }))
```

is fine and can be validated while

```
let scheme = Z.object({
    username: Z.string().min(5).max(50),
    password: Z.string().min(10).max(50),
    asyncData: Z.promise(Z.string())
  }))
```

is wrong because `scheme` does not even expose `then` method to validate it asynchronously.

**Comment by Albertbol** [comment]
Hey, thanks a lot for library, enjoying it very much, would be great if this feature would be added, I think It will open a lot of possibilities and will keep validation logic in the schema.

**Comment by vriad** [comment]
This is now available in the Zod 2 beta: https://github.com/vriad/zod/tree/v2

@chrbala @Albertbol

**Comment by Albertbol** [comment]
Thank you that's awesome ! Will test it out
