### ISSUE TITLE
Comparison with https://github.com/ianstormtaylor/superstruct

### ISSUE THREAD

**Issue by kasperpeulen** [vriad/zod#89]
I would like to know how this library compares to https://github.com/ianstormtaylor/superstruct.

Thanks!

**Comment by o-alexandrov** [comment]
Personally, I am new to [superstruct](https://github.com/ianstormtaylor/superstruct) and just played with it locally.
While the `superstruct`'s API looks similar to `zod`, `superstruct` is also a little lighter (weight-wise).

**However, there are two major issues with superstruct**:
- last reply from the author in issues was `25 days ago`
- `StructType` (utility fn to infer a type) [is not working](https://github.com/ianstormtaylor/superstruct/issues/411)

**Comment by vriad** [comment]
@kasperpeulen 

One big difference is superstruct's very functional API design vs Zod's more fluent/OOP API. 

Beyond that, superstruct is missing these features: 
- object methods: (pick, omit, partial, deepPartial, merge, extend)
- nonempty arrays with proper typing (`[T, ...T[]]`)
- lazy/recursive types
- support for parsing cyclical data (maybe) 
- promise schemas
- function schemas
- error customization

Most of this is true for all alternative libraries actually — this is roughly the list of features that initially motivated my creation of Zod in the first place. 

superstruct is a great lib and I think you can rely on @ianstormtaylor to maintain it well. If you prefer its functional approach, it's a good choice. Hope that helps.

**Comment by dimaqq** [comment]
Perhaps the above can be updated, `superstruct` docs mention `pick`, `omit` and `partial` though I dunno if the semantics are same. I didn't see `deepPartial`.

**Comment by 205g0** [comment]
@dimaqq great find
@colinhacks would you mind to update your comparison to superstruct (you compared to all other libs in the readme).

since superstruct's bundle size is just a fitfth of zod's it would be great to know if we miss any crucial feature with superstruct. if not, then a decision might be very easy

**Comment by R-Bower** [comment]
Might be time to update this comparison.  Many features have been added in the past 2 years.

**Comment by Azarattum** [comment]
Curious how it compares with v4 mini which now also has a functional API. I mainly use `superstruct` in my projects are there any advantages to switch to v4 mini?
