### ISSUE TITLE
Optional string problem (?)

### ISSUE THREAD

**Issue by SrBrahma** [vriad/zod#90]
Hello! Congratulations and thanks for this lib.

I don't know if this is an error, as I just started using it, but seems strange.

This doesn't raises errors
```
const createStoreSchema = zod.object({
  name: zod.string().max(20).optional()
}).optional();
```
But this one does

```
const createStoreSchema = zod.object({
  name: zod.string().optional().max(20)
}).optional();
```

`Property 'max' does not exist on type 'ZodUnion<[ZodString, ZodUndefined]>`

**Comment by vriad** [comment]
This is the desired behavior, but I admit the docs are confusing. `z.string().optional()` is just syntactic sugar over `z.union([ z.string(), z.undefined() ])`. Every call to `anything.undefined()` (or `anything.nullable()`) returns a ZodUnion, so you need to make sure to add all refinements to the string schema before calling those methods 👍
