### ISSUE TITLE
Potential bug with z.string().uuid()

### ISSUE THREAD

**Issue by soulchild** [vriad/zod#91]
I came across this while using zod in an express.js environment. Every other request was failing the uuid validation (`Invalid uuid`). I hacked together a minimal zod-only test-case and found out that this happens without express as well.

The second time `parse()` is called when validating a schema which uses `uuid()` it throws a `ZodError: uuid: Invalid uuid`. Interestingly, this does not happen when using `z.string().email()` which internally AFAICT does the same thing, only with a different regex.

```js 
const z = require('zod');

const schema = z.object({ uuid: z.string().email() });
try {
  schema.parse({ uuid: 'foo@example.com' });
  schema.parse({ uuid: 'foo@example.com' });
} catch(err) {
  console.log('[EMAIL] This should not happen', err);
}

const schemaUUID = z.object({ uuid: z.string().uuid() });
try {
  schemaUUID.parse({ uuid: '1a657d0c-b676-4bbf-9d18-d9ecb8547d8d' });
  schemaUUID.parse({ uuid: '1a657d0c-b676-4bbf-9d18-d9ecb8547d8d' });
} catch(err) {
  console.log('[UUID] This should not happen', err);
}
```

**Comment by soulchild** [comment]
I found a [test-case](https://github.com/vriad/zod/blob/452e50c441d396144b7410b1d7df5b03803e9f7e/src/__tests__/string.test.ts#L70) making sure that exactly this should happen. What am I missing? 😄

**Comment by vriad** [comment]
What a wild bug. The root of the problem is apparently a bug in the JS Regexp engine associated with regexes with a global flag. https://stackoverflow.com/questions/3891641/regex-test-only-works-every-other-time

I got rid of the global flag and it works fine...literally a single character change 😑 Deployed in zod@1.9.1 - just `yarn upgrade zod@latest` to get the fix.

That thing about the test case is pretty funny. If you look carefully you'll see that I deleted the last character from the second UUID, making it invalid 🙃

```ts
test('uuid', () => {
  z.string()
    .uuid()
    .parse('9491d710-3185-4e06-bea0-6a2f275345e0');
  expect(() =>
    z
      .string()
      .uuid()
      .parse('9491d710-3185-4e06-bea0-6a2f275345e'),
  ).toThrow();
});
```

**Comment by soulchild** [comment]
Yes, I saw the slight difference in the test-case shortly after submitting my comment. ;-)

Again, thanks for your quick response and releasing a fix, Colin! I really appreciate it.

**Comment by waiz3ple** [comment]
I just encountered this issue

**Comment by abeisleem** [comment]
Same

**Comment by RedSpid3r** [comment]
Also just encountered this issue on `^3.22.2`

**Comment by DylanGoodfellow** [comment]
Still getting this one on 3.22.4 @colinhacks

**Comment by PPan1215** [comment]
+1 Still getting this one on 3.22.4.

**Comment by BradyRyun** [comment]
Experienced this on `^3.21.4`

**Comment by vsapronov** [comment]
Same here `^3.21.4`

**Comment by vinibartling** [comment]
version "3.23.8" also shows this error. Is it possible to reopen this issue?

**Comment by austinm911** [comment]
I'm getting an invalid uuid error using uuid's created from https://github.com/TheEdoRan/uuidv7-js

**Comment by smurphnturf** [comment]
Also got this on 3.21.4

**Comment by beletate** [comment]
same: 3.23.8

**Comment by kelkes** [comment]
+1 3.23.8

**Comment by ptkeens** [comment]
Just ran into this on 4.1.5

**Comment by TNAJanssen** [comment]
Same here

**Comment by Tellev** [comment]
Same here on 4.3.4
