### ISSUE TITLE
Improve default error for required field

### ISSUE THREAD

**Issue by flybayer** [vriad/zod#92]
Currently passing `undefined` to a field defined as `z.string()` results in the following error message:

```
Invalid input: expected string, received undefined
```

What I want is this:

```
Required
```

Other error messages are nice by default, like "Invalid Email" and "Should be at least 10 characters".

**Comment by vriad** [comment]
This is possible with a custom errorMap:

```ts
const errorMap: z.ZodErrorMap = (err, ctx) => {
  if (err.code === z.ZodErrorCode.invalid_type) {
    if (err.received === 'undefined') {
      return { message: 'Required.' };
    }
  }
  return { message: ctx.defaultError };
};

z.string().parse(undefined, { errorMap });
```

Unfortunately this currently requires passing the custom error map into every `.parse()` call you want the custom error map to take effect. Still thinking about potential solutions to that.

**Comment by flybayer** [comment]
If you don't want to change the default error message for this (which I still very much prefer), then maybe one of the following would work:

- `z.string('Required')` (this is what I intuitively thought to try first)
- `z.string().msg('Required')`

**Comment by vriad** [comment]
Hm yeah you're right - the default error messages should be as useful as possible. Changes in zod@1.9.2.

Note that this only applies to `undefined` inputs:

```ts
z.string().parse(undefined); // ZodError: "Required"
z.string().parse(4); // ZodError: "Invalid input: expected string, received number"
```

**Comment by flybayer** [comment]
Awesome!

**Comment by acfunk** [comment]
@colinhacks  This has regressed in v4. Is that intentional?

**Comment by Lornz-** [comment]
@acfunk There's indeed a regression in v4. To get around the default required field error and use the custom one, I have to initialize the values with an empty string.

**Comment by silipi** [comment]
https://github.com/colinhacks/zod/issues/4968 opened a new one just to track
