### ISSUE TITLE
Field errors helper method

### ISSUE THREAD

**Issue by flybayer** [vriad/zod#93]
The `error.formErrors.fieldErrors` feature is super helpful!

Here's my current usage with react-final-form.

```tsx
<Form
   validate={(values) => {
      try {
        SignupInput.parse(values)
      } catch (error) {
        return error.formErrors.fieldErrors
      }
   }}
```

But it would be super awesome if instead the zod object had a function that did the above for me. Something like this:

```tsx
<Form 
   validate={SignupInput.validate} 
```

**Comment by vriad** [comment]
Since the structure of this method may vary from library to library, I'd recommend using a generic helper method for the time being:

```ts
const ZodRHF = <T extends z.ZodType<any,any>>(schema:T)=>(values:any)=>{
  try{
    schema.parse(values)
    return {}
  }catch(err){
    return (err as z.ZodError).formErrors.fieldErrors;
  }
}
```

Then you can use it like this:
```ts
<Form validate={ZodRHF(SignupInput)} />
```

**Comment by markhughes** [comment]
@colinhacks maybe an alternative would be to somehow catch and handle a callback, and return the callback? 

e.g:

```jsx
<Form 
   validate={SignupInput.catch(values, (err) => err.formErrors.fieldErrors)} 

```

**Comment by VenomFate-619** [comment]
validating with number not working

<img width="211" alt="image" src="https://user-images.githubusercontent.com/67755128/201133492-3d10a89b-cb22-43e0-8eb9-0e35618e44c3.png">

**Comment by Crisfole** [comment]
@VenomFate-619 this is months late, but you need a coerce in there:

```
mobileNumber: z.coerce.number()
```
