### ISSUE TITLE
Is Typescript 3.4+ not supported?

### ISSUE THREAD

**Issue by swayf** [vriad/zod#94]
Can not pass the unit tests with typescript 3.7

Is it planned to support only 3.9+ again ((now in beta)), but not previous versions?

**Comment by vriad** [comment]
This is a bug; just pushed a fix in zod@1.10. 

I do all development on Zod using TS 3.2. Curiously this error only occurred in TS 3.3+. This is my fault - I was just assuming forward compatibility.

Unfortunately I couldn't find a ay to fix this without causing a new error — this time only for TS 3.2. So I'm dropping support for it here (hence the minor version bump). 

Not sure I understand your question about TS 3.9?
