### ISSUE TITLE
Is there a way to set nonstrict as a default?

### ISSUE THREAD

**Issue by tamj0rd2** [vriad/zod#98]
I'm writing types for JSON responses we get from external APIs. I don't particularly want to start throwing errors if they ever add additional fields to their responses. Is there a way for me to get non-strict functionality as a default without adding it to all of my types?

**Comment by vriad** [comment]
I'm afraid not :/ 

There's no mechanism for global configurations, and it's not on the roadmap currently. I'm trying to avoid any opaque global configurations since that pattern breaks locality and makes it harder to debug things.

**Comment by eh-am** [comment]
I hate being the "+1" guy, but in this case I find appropriate to demonstrate there's a need. 

In our case, we also have JSON responses from external APIs,  and are considering converting a codebase using yup to zod, but this is something that would get in our way.

**Comment by kasperpeulen** [comment]
@eh-am You can make your own object function that does exactly this in a one liner, and use that all over your project.

**Comment by eh-am** [comment]
First, sorry for hijacking this thread.

I didn't express myself well, what would be useful for me is to have a way to set all objects recursively to be non-strict.

My use case is something like this:
https://github.com/vriad/zod/issues/51#issuecomment-629733477

where I want the type to be strict, but when actually doing the validation to be non-strict (I am validating against an API, I am only interested in a subset of the response)

As of now, I believe we could just create two versions of the same Schema (strict and not strict), and >think< I can create use a high order function to create strict/non strict objects, but not sure how the types would work.
