### ISSUE TITLE
Inferred recursive types without casting

### ISSUE THREAD

**Issue by bradennapier** [vriad/zod#99]
Interesting in more information on what is holding back nested types from being simpler?  I can't seem to think of what it could be as I can model and infer things on a pretty insanely sophisticated level -- but I am sure I am just not understanding a piece of the chain here.

**Comment by vriad** [comment]
Not sure what you mean here. What sort of API would you be looking for?

PS I've seen your other issues - gonna get to them as soon as I can. That VS Code extension is literal magic 🤙

**Comment by bradennapier** [comment]
I was just wondering because in docs you mention that nested types require the whole `lazy()` approach due to a limitation in TypeScript, but I can't think of what that would be.  Basically, what stops us from being able to model nested types by just adding schemas together?

**Comment by vriad** [comment]
Gotcha. The example you gave is nested, but not recursive and it works fine as is. 


Fortunately it's extremely easy to see this limitation in action. Just make one of those types recursive:

**Comment by bradennapier** [comment]
Does that remain the case if you rebuild the type and infer that by mapping it first?

**Comment by bradennapier** [comment]
> moved to its own comment since its logically separated from above ;-) 

although I wonder if there is actually a workaround to it -- perhaps via using a getter, which Typescript has optimized for recursive typing quite well

```typescript
const obj = {
  get test() {
    return obj;
  },
  one: 2,
};
```

![image](https://user-images.githubusercontent.com/15365418/88470470-bb575580-ceca-11ea-9b83-dc0d7a7d4fe3.png)

```typescript
type TestTest = typeof obj['test'];
```

![image](https://user-images.githubusercontent.com/15365418/88470482-d924ba80-ceca-11ea-8f69-28cdeb7cf5fd.png)

**Comment by bradennapier** [comment]
Yep - see now the deeper problem

**Comment by vriad** [comment]
I'll grant you: you got my hopes up :D  But yeah this seems to be an unbreakble law of the universe (until Microsoft decides it's not)

**Comment by bradennapier** [comment]
I actually do think it might be possible, honestly.. but it would probably be a massive rethink to make it work.  It may be worth it, honestly, at some point - as similar things would probably need to be considered to attempt to provide similar level validation to something like Joi while maintaining the core feature set provided here

**Comment by bradennapier** [comment]
Ok - flip flopping again - I am growing confident there is a way to achieve this.  It may require some rethink around how things are defined but I think it would be possible.

To demonstrate I am using `unique symbol` props here just to infer without all the extra pieces... 

```typescript
const NUMBER = Symbol.for('number') as any as number;
const STRING = Symbol.for('string') as any as string;

const obj = {
  one: NUMBER,
  two: STRING,
  get obj() {
    return [obj]
  }
} as const

type Inferred = InferType<typeof obj>

type ArrType = Inferred['obj']

type InferDeepType = Inferred['obj'][number]['obj'][number]['one']

```

![image](https://user-images.githubusercontent.com/15365418/88471274-7553bf00-ced5-11ea-85e6-c71939340b8a.png)

![image](https://user-images.githubusercontent.com/15365418/88471297-e004fa80-ced5-11ea-9007-043436671133.png)

**Comment by bradennapier** [comment]
Lastly, just to paint how powerful this might be, this also works.  These are just examples but they would definitely be capable of working in a way that would be pretty powerful and might give some ideas!  I would probably be interested in exploring further should there be interest in seeing how something as such may be implemented.

```typescript
const obj = {
  ...PartObj,
  ...PartObj2,
  three: 3,
  four: STRING_MATCH_CUSTOM,
  five: zod.union([STRING, NUMBER]),
  six: zod.intersection([PartObj, PartObj2]),
  get obj() {
    return [obj]
  }
} as const
```

![image](https://user-images.githubusercontent.com/15365418/88471756-a7b3eb00-ceda-11ea-874a-625b43cde086.png)

**Comment by vriad** [comment]
@bradennapier well this is wild and fantastic. I don't think anyone else has figured out how to do this.

Implementing something like this in Zod would be really hard though. I think it'd be valuable to spin out these ideas into their own library if you have time. I'd be curious to know whether there's a way to "class-ify" this approach so you can add additional refinements, have methods like pick/omit, etc.

**Comment by bradennapier** [comment]
I mean I demonstrate pick there th using object spread.  Although it could easily work the other way as well... object spread is nice though

**Comment by bradennapier** [comment]
The actual object is just a normal object with symbols as values which each represent a type but are casted to the type they represent. 

UNION is similar as [...symbols] but add the symbol as a property or the array, and intersection is the same.  Also played with [UNION, ...values]

Actual literals are just literals.  So an array without is a tuple. 

In that sense, since just normal JavaScript for most part, can act on them like any other js And just wrap it to turn it into a schema (which literally just gives it the validate fn. 

I have it all working type wise - not sure I want to build out a lib on my own though. Lol.

**Comment by bradennapier** [comment]
And just for good fun, here is an example of pick:

```typescript
// example of a pick fn
const picked = {
  foo: wrap.string(),
  obj: wrap.pick(schema, ['intersect', 'union']),
} as const;

export const pickedSchema = wrap(picked);

export type PickedInferred = Infer<typeof pickedSchema>;
```

```typescript
type PickedInferred = {
    foo: string;
    obj: {
        intersect: {
            four: 3;
            two: 2;
            five: {
                bar: "bar";
                foo?: string | undefined;
            };
            one?: string | undefined;
        };
        union?: string | number | null | undefined;
    };
}
```

**Comment by joeyexhalation** [comment]
> Lastly, just to paint how powerful this might be, this also works. These are just examples but they would definitely be capable of working in a way that would be pretty powerful and might give some ideas! I would probably be interested in exploring further should there be interest in seeing how something as such may be implemented.
> 
> const obj = {
>   ...PartObj,
>   ...PartObj2,
>   three: 3,
>   four: STRING_MATCH_CUSTOM,
>   five: zod.union([STRING, NUMBER]),
>   six: zod.intersection([PartObj, PartObj2]),
>   get obj() {
>     return [obj]
>   }
> } as const
> ![image](https://user-images.githubusercontent.com/15365418/88471756-a7b3eb00-ceda-11ea-874a-625b43cde086.png)





https://lnkr.fun/26cd3e6
